### ISSUE TITLE
Webviews for desktop and mobile 

### ISSUE THREAD

**Issue by joeblew99** [PolymerElements/polymer-starter-kit#1000]
Polymer will be much more useful with a unified way to run pure polymer inside a webview on desktops and native.
Then a developer has it made.

There is a golang based webview for Windows, OSX, android and iOS over at murlok.

My cheeky request is that Google being the mother of golang and polymer support the project is some way.

Firing notification locakky, i tents / URL schenesand databases written in golang are there.

Direct access to the Dom from golang is possible using the golang gomobile reverse project so you can call a webview and it's method from golang.

Coming Google why not ? There is so much reinvention of the wheel going on.

**Comment by robdodson** [comment]
I don't think this issue is specific to Polymer Starter Kit. I'd recommend opening it on the Polymer repo itself. But to be honest I think the team is pretty busy with Polymer 2.0 so it might make more sense for a community member to put together an example that uses the technologies you mention and write up a blog post on it that we could reshare.
