### ISSUE TITLE
Version number in bower.json?

### ISSUE THREAD

**Issue by akhr** [PolymerElements/polymer-starter-kit#102]
polymer-starter-kit bower.json --> "version" : "0.0.0" should it be updated to "1.0.1" ?

**Comment by addyosmani** [comment]
Good question. For our other boilerplate projects like Web Starter Kit, we opted not to bump the version number. This was intentional as it encourages end-users to think of the version field as theirs for their own projects. 

Interested in @wibblymat's take on this.

**Comment by wibblymat** [comment]
Just to follow up: I was pretty sure that the `version` field in `bower.json` was never used, but that's not quite right. The only place that it is used is as the base version for the `bower version` command that bumps the version for you.

If you don't intend to use `bower version` for bumping the version it is safe to not include the `version` at all, since the tags are used instead.
