### ISSUE TITLE
Issue when running gulp serve on polymer-starter-kit 1.0.1

### ISSUE THREAD

**Issue by akhr** [PolymerElements/polymer-starter-kit#105]
OS : Ubuntu 14.04
Node : 0.12.2
npm: 2.7.4
bower: 1.4.1
gulp: 3.9.0

Steps:
1. Download polymer-starter-kit 1.0.1
2. unzip
3. npm install
4. bower install
5. gulp serve

![screenshot from 2015-06-02 11 21 22](https://cloud.githubusercontent.com/assets/695965/7943680/df84a1ae-091a-11e5-9e82-d88f0ebe255e.png)

**Comment by addyosmani** [comment]
Could you verify that you're seeing dependencies installed in your bower_components and node_modules directories?

**Comment by addyosmani** [comment]
Verified that downloading the 1.0.1 release, npm installing and bower installing followed by a serve is working for me:

![screen shot 2015-06-02 at 19 36 54](https://cloud.githubusercontent.com/assets/110953/7943795/cac03b22-095e-11e5-9dbd-f70e191bc253.png)

It's possible that one of the installation routines was unable to complete successfully (happens due to network occasionally). I would try `npm cache clean` followed by a reinstall to see if that helps at all.

**Comment by akhr** [comment]
Yes I see the dependencies in both bower-components and node-modules.

**Comment by akhr** [comment]
`npm cache clean` didnt help. Same error

**Comment by akhr** [comment]
Both `$ gulp serve` and  `$ gulp` results in same error

**Comment by addyosmani** [comment]
I'm curious if this issue is just specific to images. What happens if you `rm -rf`/remove the `app/images` directory and try `gulp serve` again?

**Comment by akhr** [comment]
removing the images directory worked. Thank you

**Comment by addyosmani** [comment]
np. Btw, we're looking into the reason for image optimisation having issues on Ubuntu at the moment. So, while removing the directory worked here I'm hoping we'll soon have a proper fix for the more general issue.

**Comment by akhr** [comment]
Thank you Addyosmani. Are you instructions posted anywhere for adding CRISPER task to gulpfile.js for CSP stripping ?
