### ISSUE TITLE
Question about menu button

### ISSUE THREAD

**Issue by kbwatts** [PolymerElements/polymer-starter-kit#147]
Looking at the default navigation menu button (https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L91, I'm really curious about why it uses:

```
<button tabindex="1" id="paperToggle" paper-drawer-toggle>
  <iron-icon icon="menu" paper-drawer-toggle></iron-icon>
</button>
```

instead of this (or something similar):

```
<paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
```

because this way it would look and feel consistent with the other provided default buttons in the toolbar - would that not be preferable/consistent with MD?

**Comment by addyosmani** [comment]
I've previously tried using `<paper-icon-button>` for this, but don't believe `<paper-header-panel>` was correctly applying the toggle behaviour deep enough for the `<iron-icon>` to actually toggle the button from inside `<paper-icon-button>`.

That said, this was a few weeks ago and things might have changed since then. I'll try locally testing and confirm whether this is still the case.

**Comment by addyosmani** [comment]
It appears to work in the latest release :star: I've thrown together a PR for it and will cc you in just a minute.

**Comment by kbwatts** [comment]
I thought it was something like that - your PR looks good to me :+1:
