### ISSUE TITLE
Default tall banner to collapsed state on mobile?

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#175]
I noticed that the animation for collapsing the `paper-header-panel` is super janky on my Nexus 5. What do you think about defaulting it to the collapsed state on mobile? FWIW, it eats up a ton of room anyway so I kinda prefer having it collapse on mobile since I don't have much real estate.

cc @chuckh @addyosmani

**Comment by addyosmani** [comment]
I would like (if possible) for us to see if we can slim down paint time here to reduce jank on mobile first. Failing that I think your proposal seems quite reasonable.

@paullewis I don't suppose we could tempt you into helping with some jank-busting here..could we? :)

**Comment by addyosmani** [comment]
Took an initial look on an N5. 

I'm (occasionally) running into sum hefty 50ms scripting events related to scroll that appear to come from https://github.com/PolymerElements/paper-header-panel/blob/master/paper-header-panel.html#L368

![screen shot 2015-06-17 at 14 32 30](https://cloud.githubusercontent.com/assets/110953/8208151/e0d2a4e0-14fd-11e5-9128-4e4ab483a09f.png)

Otherwise, we appear to be spending a lot of time in Raster on scroll:

![79797](https://cloud.githubusercontent.com/assets/110953/8207954/b57bc6ce-14fc-11e5-9728-ef37be0c7033.png)
![5345345353](https://cloud.githubusercontent.com/assets/110953/8207956/b5826092-14fc-11e5-873a-ddaa2cca5bcf.png)
![23123231](https://cloud.githubusercontent.com/assets/110953/8207955/b57fb37e-14fc-11e5-9288-e0ffb018f4a6.png)
![8080809](https://cloud.githubusercontent.com/assets/110953/8207953/b56a99bc-14fc-11e5-8bfb-48a220505e7e.png)

I'm seeing only minor recalc styles:

![screen shot 2015-06-17 at 14 28 35](https://cloud.githubusercontent.com/assets/110953/8208067/4bfce8d0-14fd-11e5-8498-85860c962903.png)

I played around with turning the box-shadow use in the header on and off, but that didn't appear to significantly make a difference on scroll here. 

Looking at the paint profiler view, our touch event handlers may be impacting slow scroll a lil', but haven't dug in further:

![screen shot 2015-06-17 at 14 39 13](https://cloud.githubusercontent.com/assets/110953/8208324/f73e5ea8-14fe-11e5-9af9-77b0c4f34d44.png)

Timeline exports for anyone that gets a chance to look at this further: https://drive.google.com/a/google.com/folderview?id=0B5lvyM01phJQfnBmOWNmbTh0UDAwQ29QQ3AtTHdVY3hPd0tQTzM5amlaVTlwdk0zdFRRc00&usp=sharing (currently only accessible to Googlers, but can add if exploring further and not)

**Comment by addyosmani** [comment]
Side: if you don't want to pull down all our tooling, there's a one-click light download option available in https://github.com/PolymerElements/polymer-starter-kit/releases that has the same scroll perf issues.

**Comment by paullewis** [comment]
So what seems to be happening is this:

* The header transitions on height. This is going to cause the whole page to repaint because layout changes for the whole page and page content moves.
* The header itself will need to be repainted. This is less of an issue than the above.
* As a side note you don't have GPU raster on. Today that would need a viewport of `width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes` but eventually it shouldn't be so magical.

My suggestion, which may not be feasible:

* Change the content to have a padding that accounts for the header's height
* Change the header to `position: fixed`
* Break out the background block and title to separate, promoted elements (`will-change` or `backface-visibility: hidden`)
* Use JS to toggle classes in a scroll handler. The classes should manipulate scale transforms

We should avoid changing height. It's causing the whole page to repaint, which makes this header animation proportional to the DOM size (layout) and page height and complexity (paint). By doing the alternative version we will only trigger composite, and page content won't jump, either.

**Comment by chuckh** [comment]
Pull request #233 which migrates to paper-scroll-header-panel fixes the jankyness.

**Comment by addyosmani** [comment]
As the jank issues were addressed in https://github.com/PolymerElements/polymer-starter-kit/pull/233, closing as fixed.
