### ISSUE TITLE
"Search" icon is non-functional

### ISSUE THREAD

**Issue by salamanders** [PolymerElements/polymer-starter-kit#176]
The "reload/refresh" icon and the "search" magnifying glass icon both seem to do nothing.  Would be nice to have everything functional, or hidden.

Search would e a great place to show off whatever polymer can do for the always-challenging "search with auto-complete substring matching" use case!

And what does "reload" do anyway?  If updates are pushed live firebase style, I don't get the point of the button.

**Comment by flaiker** [comment]
I assume this are just placeholders and so by design just to show where you could add your iconbar. I'd say implementing search functionality etc. is way over the top for a boilerplate where most people will just remove it again.
In my opinion this is not a showcase for functionality but rather a starting point with best practices.

**Comment by arthurvr** [comment]
:+1: to what @flaiker said.

**Comment by addyosmani** [comment]
:+1: to @flaiker's comment. I had considered adding in proper search functionality and reload, but that would be way OTT for a starting point. The purpose of the icons is to inform the user that:

1) There's a region available for including icons
2) Demonstrate how these icons can be included

For the sake of staying as lean as we can, I think we should avoid adding in further functionality that hooks up to these buttons.
