### ISSUE TITLE
Compatibility with PolymerElemets/app-layout-templates

### ISSUE THREAD

**Issue by decurgia** [PolymerElements/polymer-starter-kit#179]
Hi all

app-layout-templates are mentioned in the starter-kit's home section. But those templates aren't easy to integrate as they do have got a different setup as the polymer-starter-kit.
I tried to integrate the "Left Nav + List + Detail" layout, without success.

Why does the polymer-starter-kit has got layout code in the <body> while the app-layout-templates to have got the code in the <x-app> element?

Cheers
-luca.

**Comment by addyosmani** [comment]
Thanks for the question @decurgia. I assume you're referring to the structure used in https://github.com/PolymerElements/app-layout-templates/blob/master/list-card-over/src/x-app.html and so forth.

@frankiefu works on app-layout-templates and may have a good answer for this :) Paraphrasing: is there a reason why we include templates inside elements rather than at a document level there?

It would be great to investigate whether there's anything we can do to lower the friction of getting started with (or integrating) the app templates project better. If not in that repo, perhaps as part of an accompanying one that makes usage more drag/replace.

**Comment by SilverPaladin** [comment]
I use a framework called Laravel, and it handles this well. Inside your layout template you have placeholders for content. Conceivably, we could modify the sample layouts and the PSK to place relevant content inside an element layout template? If the layout templates were constructed with some type of guideline, it would make it easier to share different layouts with each other.

**Comment by addyosmani** [comment]
The app-layout-templates are currently being rewritten and our plans are to rework some of the layout architecture in PSK once they are ready to make it easier to drag/drop templates you want to use. This probably won't be ready for another few months, but it's definitely on our radar.
