### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by rchrdnsh** [PolymerElements/polymer-starter-kit#196]
i set up my project and run 'gulp serve' and the app does not show up in the browser. Then I get this message in the browser: "This webpage is not available. ERR_NAME_NOT_RESOLVED. The picture goes into the details...
![screen shot 2015-06-19 at 11 17 34 am](https://cloud.githubusercontent.com/assets/7884263/8260378/0da67a70-1678-11e5-970d-b4365962c8f1.png)

**Comment by addyosmani** [comment]
Could you provide more details? Operating system, version of Polymer Starter Kit and whether this was after installing all deps as noted in the readme?

**Comment by addyosmani** [comment]
Friendly ping for more info.

**Comment by nosilleg** [comment]
@rchrdnsh It may be that you're missing the colon in the URL for the port number.

http://localhost:3000/

**Comment by addyosmani** [comment]
@rchrdnsh This issue generally happens when a `gulp serve` is accidentally closed/killed in the terminal or one accidentally navigates to the wrong localhost path. I would double check that Gulp and the other npm dependencies are installed and try running `gulp serve` again. If you're still running into issues here, please provide us some additional information (e.g what else is displayed in the terminal when this fails) and we'll take another look into it. Thanks!
