### ISSUE TITLE
Files in app/precache.json are discarded

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#214]
I had imagined that if I added paths to `app/precache.json` that it would get merged with everything else in the [precache gulp step](https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L164) but that doesn't seem to be the case. Is this kind of thing discouraged or is it an oversight?

**Comment by robdodson** [comment]
I wrote a PR @addyosmani @jeffposnick would either of you have a moment to review?

**Comment by jeffposnick** [comment]
I want to make sure I understand the issue: are you manually adding resource paths to `precache.json` in the `app/` directory, and then you want to merge those manual additions with whatever gets picked up via globs in `dist/`?

If that's the use case, then have you considered just including the manually-managed paths as an array that you explicitly assign to the `precache` attribute of `<platinum-sw-cache>`? I'd consider that a cleaner approach, and that array is already automatically [merged](https://github.com/PolymerElements/platinum-sw/blob/master/platinum-sw-cache.html#L104) with the array that comes from `precache-file`.

Alternatively, if there are resource paths that you want precached that aren't being picked up by the existing glob patterns, maybe we can just change the default patterns or offer another way of customizing them?

**Comment by robdodson** [comment]
> I want to make sure I understand the issue: are you manually adding resource paths to precache.json in the app/ directory, and then you want to merge those manual additions with whatever gets picked up via globs in dist/?

yes

> If that's the use case, then have you considered just including the manually-managed paths as an array that you explicitly assign to the precache attribute of <platinum-sw-cache>?

I did but there are a couple issues.

1. If you do put paths in `app/precache.json` they will be used when you run `gulp serve`. After you create a build using `gulp` they're no longer there. That part caught me off guard and seems like others would fall into it too.
2. I actually thought it was kind of nice being able to put the elements I wanted to cache in a separate json file. I preferred that approach to having it in my markup. I guess it's just personal opinion.

> Alternatively, if there are resource paths that you want precached that aren't being picked up by the existing glob patterns, maybe we can just change the default patterns or offer another way of customizing them?

I think the default globs are fine. I was including an image I wanted cached and rather than cache the entire images dir, I wanted to show how to just cache one image for a tutorial. Right now the best way to do that is to add it to [the `files.push` call](https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L171). IMO it was just a nicer experience to put the stuff I wanted cached in a simple JSON Array, vs having to manually edit my gulpfile, which is a process some folks may shy away from.

I guess I'm wondering if there are major reasons why you think we shouldn't put stuff in `app/precache.json`. I just did it because it felt convenient at the time.

**Comment by robdodson** [comment]
Slight correction

> Right now the best way to do that is to add it to the files.push call.

I mean, other than putting the paths in your markup, the best way to do it is to edit the gulpfile.

**Comment by robdodson** [comment]
Actually now that I think about it... If I tell `platinum-sw-cache` to use the `precache` attribute, instead of the `precache-file`, will it *exclude* the `precache.json` entirely?

**Comment by jeffposnick** [comment]
I called out the fact that they could be used in conjunction with each other in [the docs](https://github.com/PolymerElements/platinum-sw/blob/master/platinum-sw-cache.html#L62), but that's obviously easy to miss.

Some background that colors my thinking: I didn't intend to create a "dummy" `app/precache.json` to begin with, but [it was needed](https://github.com/PolymerElements/polymer-starter-kit/pull/24) to prevent errors from being logged when running in the dev environment. I wish that it was possible to include comments in a JSON file, which would help clear this up.

I think you should just modify the existing glob patterns in your copy of the project to remove the pattern that matches the entire images directory, and then either add a pattern that matches only the specific file you care about, or list the file in the `precache` attribute.

There are already two ways of accomplishing this, and adding in support for a third seems like it would add to the confusion instead of simplifying things.

**Comment by robdodson** [comment]
After working on this for a while longer I'm fine closing the PR since I don't think it adds much value. If you were going to add only one file it's probably easier to do it with the attr and if you want to add multiple files it's probably better to use the globbing patterns in gulp.

However I do think there's an issue here still. My natural inclination was to add stuff to `precache.json` since that's what PSK points to by default, and it works when you run `gulp serve`. Which made it seem like I was doing the right thing. Because `precache.json` is just an empty array it almost invites someone to do it.

> I wish that it was possible to include comments in a JSON file, which would help clear this up.

Could we use something like JSON.minify to strip comments out of the JSON file? http://stackoverflow.com/a/3104376/1019180

Relevant quote from Crockford:

> Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like. Then pipe it through JSMin before handing it to your JSON parser. - Douglas Crockford, 2012

Or maybe throw an error in gulp if `app/precache.json` isn't empty?

**Comment by jeffposnick** [comment]
To close the loop on this, `<platinum-sw-cache>` will be moving to a JSON configuration file that contains an object instead of just a single array (see https://github.com/PolymerElements/platinum-sw/pull/52).

This will make it possible to include a `"README": "Do not edit this file."` (except something more verbose) in the `app/cache-config.json` that gets checked into PSK, and that will hopefully prevent confusion.
