### ISSUE TITLE
Where can I find the Paper Reader showed in Google I/O 2015?

### ISSUE THREAD

**Issue by xi3** [PolymerElements/polymer-starter-kit#226]
Thanks

**Comment by arthurvr** [comment]
I doubt it's public yet. @addyosmani?

**Comment by surma** [comment]
Let me quote @addyosmani: “Hopefully sometime in July”. We have to update to the new Firebase elements first so you can enjoy the reader in all its glory :smiley: 

https://twitter.com/addyosmani/status/614528138844856320

**Comment by arthurvr** [comment]
Okay I'll guess we can close the issue then. Thanks @surma!

@surma @addyosmani Unrelated thought: _Building something and then open-sourcing it is kinda the wrong order. That's not the deal with **open**-source. Being OS means more than having the code live somewhere online. It means doing the work in the open and it means having people involved with the decision-making._

**Comment by addyosmani** [comment]
As @surma mentions, we still have an amount of rewrite work left to go here as well as the usual rounds of performance and accessibility fixes need to be completed before the project gets released. We'll be doing our best to get this out in July :)

@arthurvr Perhaps some context is useful as we would otherwise love to be developing in the open. The open-source process for projects at Google requires that we go through multiple stages of review for any code that's to be shared in public. That includes security, engineering readability, legal and so on. 

Because of the way this process is structured, we're can't yet develop in the open until a reviewable version of the end-product is in that launch pipeline. In the case of Paper Reader, the app isn't in a review-ready state as yet and we couldn't release the early version and iterate. 

This can definitely feel less than ideal from an openness perspective, but we take any comments about how this process can be improved on-board and try to feed it back to the open-source team.

**Comment by addyosmani** [comment]
Closing as not part of PSK, but we will announce when the app is ready and do a writeup @xi3

**Comment by niutech** [comment]
Any update?
