### ISSUE TITLE
 Where to put element-specific resource files?

### ISSUE THREAD

**Issue by danhawkes** [PolymerElements/polymer-starter-kit#228]
Intuitively, I want to put them in the element's directory, e.g. `elements/my-element/resource.json`, and reference them with a relative path like `…url="resource.json"`.

This works in the `serve` build because it serves directly from the `app/elements` directory, but not in the `serve:dist` build, because it [only copies html files][1] into dist (presumably just for vulcanization).

I guess what I'm asking is: should the `copy` task move non html/js/css files in element subdirectories into the dist/elements directory? E.g.
 
    elements
        my-element
            resource.json
            some-directory
                file.txt

    elements
        resource.json
        some-directory
            file.txt

Obviously it'd have to deal with collisions somehow (throw error/namespacing?).

Alternatively, if it's assumed that resource files are placed somewhere relative to the root (like images are now), how can they be referenced inside an element without using absolute paths?

  _(Migrated from [generator-polymer#203](https://github.com/yeoman/generator-polymer/issues/203))_

[1]: https://github.com/yeoman/generator-polymer/blob/master/app/templates/polymer-starter-kit/gulpfile.js#L96

**Comment by addyosmani** [comment]
This is a good question. In my own projects, I tend to keep assets local to each element in their own subdirectory. This makes it easier for me to refactor them into reusable components for sharing later on. It's also valid in an app to just have them in a central location, depending on the asset type. What I would do is update `copy` to move non-default files into dist/elements or alternatively structure your app so that these files are located in a location that isn't going to vastly change between `serve` and build.
