### ISSUE TITLE
Create more examples/templates

### ISSUE THREAD

**Issue by slidese** [PolymerElements/polymer-starter-kit#236]
It would be a good idea to have a bunch of different examples/templates to start from. I'm thinking of something like the collection of examples Bootstrap has: http://getbootstrap.com/getting-started/#examples

[EDIT]: A couple of days after I posted this issue the Material Design Light (http://www.getmdl.io/templates/index.html) was released. The templates found there would be nice to have for Polymer as well.

**Comment by Alienuser** [comment]
Hello @slidese 
There is a very small collection of templates for polymer:
https://github.com/PolymerElements/app-layout-templates

**Comment by slidese** [comment]
Yes, I've seen them. But those are pretty much the same kind of app. I'm looking for examples that go beyond the master-detail type of site.

**Comment by addyosmani** [comment]
We may end up porting over some of the MDL templates to Polymer Starter Kit, but it's going to take some time to do so. MDL implements adaptive UI components in the MD spec like the grid, which we don't yet have an equivalent for in Polymer 1.0 (just yet). That said, I'll keep this issue open as a reminder we should plan to do some porting.

**Comment by addyosmani** [comment]
We're currently reworking our layout elements over at https://github.com/PolymerLabs/app-layout and will be working on a new set of templates there. The idea will be that you'll still manually hand pick the templates you might want to use, but they won't be baked into PSK so that it stays lean. We are going to make it easier to just drop these templates in and have them work but it'll be another few months before this work is ready.
