### ISSUE TITLE
index.html in dist not displaying

### ISSUE THREAD

**Issue by calebeby** [PolymerElements/polymer-starter-kit#239]
I ran `gulp` to create an optimized version of my code. Everything in the `dist` folder looks normal. The issue is, when I open `index.html` in my browser, it displays a blank page. When I view the source of the document, it shows what I would expect, a very compacted version of my code. It looks like it has everything that it needs to display the page, but for some reason, it doesn't. Any ideas?

**Comment by robdodson** [comment]
Check for 404s in the devtools

**Comment by addyosmani** [comment]
@calebeby as Rob mentioned, have you seen any exceptions in DevTools console indicating that some imports might not have made it through?

**Comment by marioAnfiled** [comment]
I have a very similar issue. I have used gulp to create the dist folder then posted this on my server and get a blank page in the content area. Once I press my home button then my content shows up. Any ideas? Here is a link to my app. 

http://www.anfield-hq.com/ir-ntp2015/index.html

**Comment by totrash** [comment]
It`s because a misssing .bowerrc file in latest 1.0.3 release ......

Quick fix is to add .bowerrc file in main folder (polymer-starter-kit-1.0.3)(the one with bower.json file)
and it should contain: 

<code class="js">
{
  "directory": "app/bower_components"
}
</code>

You can delete existing bower_components folder in main folder and then run 

<code class="js">
bower install....
</code>

P.S Of course you can manually move "bower_components" from main folder to "app" folder and it will be a most quick fix to see a content

**Comment by calebeby** [comment]
@totrash I already have a copy of bower_components in the app folder. I don't understand the first part you said.

**Comment by calebeby** [comment]
@robdodson How do I check the DevTools

**Comment by robdodson** [comment]
cmd+option+j or ctrl+alt+j i believe. Also View > Developer > JavaScript Console. If there are 404s they should be displayed there.

**Comment by calebeby** [comment]
Any idea what this means?
![image](https://cloud.githubusercontent.com/assets/13206945/9151648/da002784-3dbe-11e5-81e3-a9d73861f1b2.png)

**Comment by robdodson** [comment]
Are you running `gulp serve:dist` to test the distribution? Polymer requires you use a server to test (this is because HTML Imports us ajax which isn't supported by browsers when you're serving with file:// urls).

To test your source as you edit you can run `gulp serve`. To test the site after it has gone through the gulp build process and been minified/concatenated/optimized you can run `gulp serve:dist`.

**Comment by calebeby** [comment]
@robdodson Thanks! That helps a lot.
