### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by DmitryAuine** [PolymerElements/polymer-starter-kit#279]
For example if we use dom=shadow, styles of left-bar are diffrent

**Comment by addyosmani** [comment]
To help us understand what's breaking here, can you provide some more details? For example, screenshots of what styles you're referring to in the left hand bar are different?

**Comment by arthurvr** [comment]
Friendly ping @DmitryAuine.

**Comment by DmitryAuine** [comment]
i am to lazy. U can just enable shadow and you will see that left menu has different style from shady

**Comment by robdodson** [comment]
The issue I saw was that the color and background for selected items was not correct.

**With shady dom:**

<img width="517" alt="screen shot 2015-12-19 at 7 50 35 am" src="https://cloud.githubusercontent.com/assets/1066253/11913891/e16e4902-a627-11e5-9497-6065cf00e6b4.png">

**With shadow dom:**

<img width="492" alt="screen shot 2015-12-19 at 7 50 47 am" src="https://cloud.githubusercontent.com/assets/1066253/11913894/e56103b0-a627-11e5-98cf-b8589e21dd96.png">

Should be fixed by #617
