### ISSUE TITLE
Routing, page.js, and hashbang

### ISSUE THREAD

**Issue by Frikki** [PolymerElements/polymer-starter-kit#284]
For whatever reason `page.js` has been chosen as default router, the `hashbang` option is really buggy. `page.js` is even considering removing this feature, see https://github.com/visionmedia/page.js/issues/229

It would probably be wise to leave the `hashbang` option out of `routing.html`.

**Comment by arthurvr** [comment]
Aren't we forced to use hashbangs because of browser support?

**Comment by robdodson** [comment]
We use hashbangs because we haven't setup a local sever that always sends down the index page. It's a little tricky because we *could* probably setup our gulp server to do this, but then when someone goes to deploy their site they may not realize that they need to configure their own server with the same behavior. I'm not saying that's a reason to stick with hashbangs, I agree we probably need to move off of them, but that's reasoning behind the current setup.

**Comment by arthurvr** [comment]
Ah, thanks @robdodson.

**Comment by addyosmani** [comment]
As @robdodson correctly mentioned, removing it wouldn't pose problems for us during local development, but does become a major hassle later on during user-deployment. Looking at the upstream Page.js issues, it appears that they're eventually going to break this out into a dedicated plugin. I imagine PSK would (at least for a while) switch to using that, until we can come up with a better deployment story that doesn't involve a lot of configuration. 

Right now quite a few folks trying out Polymer for the first time are deploying to GitHub pages and the like. We'll want to make sure we can guarantee routing continues to work there before dropping the hashbang option completely.

**Comment by gedw99** [comment]
@robdodson 
I am having exact same issue. hashbangs  - Urggg ugly.

For Dev and Prod, i just use a golang server in appengine with the correct settings for now

**Comment by robdodson** [comment]
@gedw99 yeah i also don't use the hashbangs in production, I just make my server work with the pretty urls

**Comment by samccone** [comment]
woot resolved by the work and recipe here
https://github.com/PolymerElements/polymer-starter-kit/commit/7082366bc258ae748837d3adfe754e70955180f9
