### ISSUE TITLE
Can't get file error 404

### ISSUE THREAD

**Issue by kenny0202** [PolymerElements/polymer-starter-kit#290]
When running "gulp serve" my application was able to start, but I noticed in the network requests that main.css, web-component-lite.js, app.js and elements.html were all error 404. It is weird because when I checked the file directory all files were there. I have also looked at the paths if it was correct and it is. Any reason or any way I can fix this? Right now the page is being loaded, but displays a blank white page.

**Comment by addyosmani** [comment]
Could you confirm what version of PSK you're using? It's odd that the files are in their expected locations but aren't being correctly served up. I'd also check if this is similarly the case when you just run `gulp` so we have a little more to go on.

**Comment by kenny0202** [comment]
I am using Polymer Starter Kit 1.0.3. 

I am not really sure how to open the "gulped" version of the application properly. As this is how my file structure looks like below. "App" containing the original project not optimized and "dist" is the optimized version. (in the app and dist folder the both contain a bower_components folder with all the elements)

Opening the gulped version with a url of "file:///D:/wamp/www/starter/dist/index.html" 

It failed to load the 4 same files, but this time beside it stating "net::ERR_FILE_NOT_FOUND"

![polymer](https://cloud.githubusercontent.com/assets/4167259/9127999/2f69e5be-3c77-11e5-94ee-25d3e84bd0c4.png)

**Comment by robdodson** [comment]
Yeah you can't run a polymer app off a file:// url because the HTML Imports polyfill uses ajax which is not supported for file:// urls. It has to be a local server.

When you run `gulp serve` it's starting up a local server for you and it serves the `app` directory. If you run `gulp serve:dist` it will serve the `dist` directory.

I'm wondering if maybe you're seeing 404s because you opened the app once, service worker tried to cache some stuff, you turned the server off and then refreshed the page.

Try this:

- Run `gulp serve`
- Go to `localhost:3000` in an incognito window in Chrome (this will ensure there's no service worker cache)
- See if there are any 404s in the console

**Comment by kenny0202** [comment]
Ok, So that's why polymer pages never loaded on a local file system. I have been using WAMP this whole time and not gulp. Which works fine, but I wanted to start using the gulp functions as I can eventually vulcanize everything and optimize it. I didn't know you can do gulp serve: dist, to serve other file directories. 

I will try the incognito option when I get the time. 

Thanks @robdodson and @addyosmani.

**Comment by robdodson** [comment]
Yeah to serve the source you'll want to use `gulp serve`. This is especially important because the `bower_components` directory is outside the `app` directory and `gulp serve` makes the paths work out correctly. http://yeoman.io/blog/bower_components-in-project-root.html

When you run `gulp` it all gets combined so you can then serve that from wherever I think

**Comment by kenny0202** [comment]
@robdodson 

So I tested the PSK gulp serve localhost:3000 in an incognito browser. It seems that the 4 files are displaying error 404.

**Comment by robdodson** [comment]
that's pretty weird. You've verified the files are in the right spot? Can you post a screenshot of the console?

**Comment by kenny0202** [comment]
@robdodson 

Yup. The files are in the right directory.

Here is the screenshot.

![polymer](https://cloud.githubusercontent.com/assets/4167259/9240426/06102e3c-411b-11e5-85ac-de16f53580f8.png)

**Comment by robdodson** [comment]
hm those URLs look wrong, it shouldn't be `localhost:3000/starter/app/styles/main.css`, it should just be `localhost:3000/styles/main.css`. Did you change the URLs in the source when you were previously trying to launch the site with WAMP?

**Comment by kenny0202** [comment]
oh ok, I found the problem. It is because I changed the base url for routing purposes. I had this at the top of index.html.  (base href="/starter/app/") for making url routing cleaner.

**Comment by robdodson** [comment]
For routing you should be able to use routes like `/foo` without needing the base url bit. Going to close this issue since I think we've found the culprit.

**Comment by kenny0202** [comment]
@robdodson  Thank you so much for the help and your time as well.

**Comment by robdodson** [comment]
sure thing :)

**Comment by kenny0202** [comment]
Sorry to bother again. So I have a iron-form in my application that has an action to scripts/addPost.php as well as an iron-ajax that has url to scripts/getPost.php they both return 404 even though the files are there. This occurs when I run gulp serve, wamp on the other hand works fine.

**Comment by robdodson** [comment]
gulp serve isn't going to run a php server so those files won't get interpreted. If you really need php support then you'll want to probably do everything in wamp and then make sure that when someone requests something from bower_components that it routes that request to the right directory and serves the correct static content.

Since this isn't an issue with the library I'd suggest opening a StackOverflow thread if you need help setting that up

**Comment by kilombo** [comment]
Hi, related to this, maybe @robdodson you can help me, i have my webapp working perfect on https://polymer-yeoman.firebaseapp.com/ but, when i use Phonegap build to test it with my Android 6.0, the homepage is not loaded and when i use a menu link i get the error: net::ERR_FILE_NOT_FOUND(file:///users)

I´m very interested on use Polymer on my mobile web apps.
Thanks !

**Comment by Dragod** [comment]
@kilombo had same issue with cordova, To solve it I went in C:\Users\Yourname\AndroidStudioProjects\yourapp\app\src\main then created a new folder called android_asset and inside that I did copy the content of dist folder that you have once you run gulp from cmd line. I have no idea why I need to do it, but it's working. Ps. I use cordova and android studio to build my APK so I'm not sure how to help with phonegap but the error was exact same. Unfortunately there is no documentation on what work on mobile devices. I found couple of bug & the  app is not really responsive. As well redirect is not working, neither popup even if it has a workaround with cordova plugin. I have an hard time to make my mobile PSK working. Good luck.

**Comment by kilombo** [comment]
Thank you very much @Dragod. I still testing. I read told by @addyosmani the google team is working on a new routing system, may be this is the solution:
https://github.com/PolymerElements/polymer-starter-kit/issues/265#event-441241845

**Comment by msi-matthew** [comment]
When serving via localhost (`polymer serve`) behavior was fine.
Once deployed on hosted from Windows IIS was getting this error.
Part of the path substring contained `/bin/`. 
Once changed to a different folder name the issue was resolved.
