### ISSUE TITLE
Isn't Polymer for Windows developers?

### ISSUE THREAD

**Issue by oswaldomilet** [PolymerElements/polymer-starter-kit#305]
Hi guys,

Since version 0.5 I had problems with environment setup to develop using Polymer. Now, my dream is to use Polymer (conceptually is the best tool for developers I guess) with Visual Studio (which for me is the best IDE). However, I always give up on installation. Have you (PSK creators) tried to use this in a Windows machine or are you targeting only OSX/Linux developers?

First, I realized that it would be necessary to install python (but < v3.0) and it's ok. Second, I got this error on npm install:

![polymer error](https://cloud.githubusercontent.com/assets/10772835/9234425/2b475f88-410f-11e5-97d1-e6a086559167.PNG)
> Using Windows 10

Thank you for this wonderful work giving us Polymer, but I think it have 3 good reasons for not everyone using it in production projects by now:
- Web components browser support (polyfill help us, waiting for others vendors wake up)
- Installation is hard (there are many windows developers trying to use it)
- Polymer elements better documentation (I guess it's an in progress work, so ok for now)

So, my main issue now is installation, could you help me?

Thanks very much

**Comment by mcnameej** [comment]
Couple of thoughts...

__(1) This is a general problem of node/npm on Windows and isn't unique to Polymer.__

Node modules that include native code need to compile/link that code during ``npm install``, which means having a C++ toolchain available.  This isn't a big deal on POSIX, but can be a major hassle on Windows.  The only good news is that it's a one-time hassle, and once you get it working for one module, it should work for all of them.

__(2) It looks like you have Visual Studio 2015.  Did you choose to install all the C++ bits?__

Your error message says the Windows SDK wasn't found.  I would expect the SDK to be installed if you install all the C++ bits.

Things changed in VS 2015 -- the C++ bits are not installed by default (see [Visual C++ Team Blog](http://blogs.msdn.com/b/vcblog/archive/2015/07/24/setup-changes-in-visual-studio-2015-affecting-c-developers.aspx)).

__(3) Do you also have have Visual Studio 2013 installed?__

I believe node is built with VS 2013.  I'd recommend using the same version to build native addons.  I'm not sure if this is required, but it seems like a good idea (easy for me to say, since I've got all the VS versions installed on my primary dev system).

npm (via node-gyp) will try to use the newest version of VS it finds on the system.  To force npm to use VS 2013, run ``npm config set msvs_version 2013 --global ``.

**Comment by arthurvr** [comment]
The error you're getting looks like a problem with Browsersync, not directly with PSK's setup.

> Have you (PSK creators) tried to use this in a Windows machine or are you targeting only OSX/Linux developers?

PSK totally wants to be cross-platform :)

> Node modules that include native code need to compile/link that code during npm install, which means having a C++ toolchain available. This isn't a big deal on POSIX, but can be a major hassle on Windows.

We try hard to avoid them as we know they can be a pain, but in this case we don't use them directly and it's a really common dependency so I'd classify this more as an issue with your local setup than a PSK issue. FWIW, I was able to setup everything on Windows.

**Comment by arthurvr** [comment]
Looking at the limited stack, could this be related to https://github.com/PolymerElements/polymer-starter-kit/issues/241?

**Comment by oswaldomilet** [comment]
Thanks @mcnameej and @arthurvr, I'll try your tips.

**Comment by arthurvr** [comment]
Was you able to archive anything @oswaldomilet? It's more of an issue with your local setup (or with browser-sync, but I doubt that) than with PSK though, so maybe we should close this.
