### ISSUE TITLE
✨ Recipe for SEO ✨

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#367]
A great question from the panel: https://youtu.be/mw0ozps3jLM?t=63

But I think people want some hard specifics :sparkles: 

@tjsavage any pointers on this one :)

**Comment by arthurvr** [comment]
Why does this need to be a PSK recipe? Most "rules", tricks and tips would apply to any polymer app and I feel like a better fit for the actual docs site. WDYT @arthurevans?

**Comment by ebidel** [comment]
Agreed with @arthurvr. SEO is a tricky one. Generally, anything that applies to a SPA applies to Polymer-based apps (e.g. use anchors, have deep links, prefer regular urls over `#` fragments), use canonical links, meta info, etc.)

**Comment by arthurevans** [comment]
Agreed. I think we have some ideas on this that aren't captured on the site. We should probably make sure PSK isn't using any anti-patterns. But I'll move this over to the docs repo. And suggest that @ebidel write an article on it :D

**Comment by samccone** [comment]
> I feel like a better fit for the actual docs site

I agree here (: ... That said, I also think a large % of people using polymer start with PSK so putting the docs / recipe here initially is a decent proving group -- once things seem stable we can elevate to polymer docs proper.

but hahah ok lets just file it over on the top level docs repo

surrryyyy :crying_cat_face: :crying_cat_face: :crying_cat_face: :crying_cat_face:

**Comment by samccone** [comment]
@arthurevans @ebidel -- the major question in my mind was how to "prerender" on the server or is that even a valid concern

**Comment by ebidel** [comment]
It's a client-side technology. Pre-constructed shadow trees has been brought up in the past, but there's no movement on it, at least as of yet. Most important thing we learned from IOWA is that Google/search needs to see markup and it needs to be able to navigate your pages.

**Comment by samccone** [comment]
@ebidel  does that mean that it might be ideal to use content inside of custom elements to expose these sort of "nav" elements?

```html
<x-nav>
  <a href="page1">page 1</a>
  <a href="page2">page 2</a>
  <a href="page3">page 3</a>
</x-nav>
```

**Comment by ebidel** [comment]
Yes

**Comment by arthurevans** [comment]
@samccone (Re: prerendering) Our experience on the docs site suggest that it's not necessary. Both docs site (running on Polymer 0.5.x) and the element catalog (running on Polymer 1.x) seem to get indexed on Google and other search engines.

Testing a few queries on other search engines (I tried Bing, Yahoo, and DuckDuckGo), I saw enough hits to suggest that they're also indexing the contents. For example "polymer auto-binding templates" brings up the right page on all of the engines, even though those search terms aren't in the title or URL, which suggests that it's not just using metadata.

There are some inconsistencies -- for example, the search "polymer paper-input site:elements.polymer-project.org" on DuckDuckGo brought up the right page first -- but the title is generic; and if you don't limit the search to the site, this page doesn't rank highly (possibly because of the generic title). It might be that they're detecting the _content_ switching at runtime, but not the _title_ switching at runtime. Which is something that's likely to affect any SPA, regardless of technology.

**Comment by samccone** [comment]
ping @peterblazejewicz for any input :)

**Comment by peterblazejewicz** [comment]
@samccone :dancer: 
I've not yet have real project with Polymer (:sadface:). The recent SPA we have made supports HTML5 History and pretty links and this is something I would recommend. So yes, it is not easy for people starting using SPA (or here Polymer) and sell it to the world.
I'd think of using JSON-LD (the link just for reference: http://json-ld.org/) and I though it is supposed to support dynamic content change on web site. This make web components markup and other details  non-relevant to crawlers.
Let me try how TTS works with Polymer.

**Comment by albertolobrano** [comment]
what is the status of this? where can i find some information in order to seo optimize a site done with polymer

**Comment by robdodson** [comment]
@albertolobrano there's no official guide but recently google search team has publicly said that they run javascript against pages that they fetch, and in the case of polymer/web components, the search engine crawls the composed dom (so basically all of your elements plus all of your content, regardless of shadow dom).

This means you can use a tool like [fetch as google](https://www.google.com/webmasters/tools/googlebot-fetch?pli=1) to verify that your site is showing up properly in search. Anecdotally, if you look at our element catalog you'll see that it shows up in search (google "polymer iron-ajax") but the catalog itself is just one big polymer element

**Comment by oneezy** [comment]
That's great news @robdodson ! I'm about to jump on my first client project w/ Polymer.

**Comment by kungufli** [comment]
@ebidel @robdodson Unfortunately we still have serious problems with Google search indexing, it seems it refuse to index our Polymer home page.

**Comment by robdodson** [comment]
Can you share a link to the site?

**Comment by kungufli** [comment]
@robdodson Sure, here it is: https://www.cerberusapp.com.

**Comment by robdodson** [comment]
@kungufli it looks like it's being indexed to me. If I search for "cerberusapp" I get a 3rd item result.

**Comment by kungufli** [comment]
@robdodson The problem is that Google seems to point only to the /help URLs, so the home page (that is reachable at / or /home) is not present at all in search results. The strange thing is that /home and /help point to the same SPA, that show different content depending on the URL path.

**Comment by robdodson** [comment]
@kungufli Depending on when the site itself went up it may take a number of weeks to properly index all of the pages. It's also possible that /help is more content rich than the home page and is scoring higher but I honestly don't know there, I'm not an SEO expert.

But I don't think the issue has to do with Polymer, I think it likely has more to do with the amount of time the page has been in the index, and the amount of content and traffic that they're getting.

**Comment by kungufli** [comment]
@robdodson The website has been online for four months now, however we made various changes during this time to try to get a better indexing. We'll wait some other weeks to see if the index will improve. Many thanks for your help!

**Comment by oneezy** [comment]
@kungufli
have you had any positive results with your SEO? 

@robdodson and Polymer team
Search is such an important factor as you guys know..and it still seems to be a huge problem w/ SPA's along with our up and coming acronym, PWA's.

Meta data title and descriptions + OG meta data for our social platforms are all part of delivering that great experience to our users.

I joked earlier and said.. 
"SEO?...There's an element for that! "

But the reality is, there is no element for that. It's a bit of black box.

Rob, I'm going to make a special request and ask for your next Polycast to be a deep dive on the Polymer SEO topic. I think it would be a great follow up with new and improved < app-route > ;)

All of you guys are doing amazing work! Seriously changing up the game. 

Keep crushing it.

**Comment by peterblazejewicz** [comment]
@ebidel 
Eric, the IO2016 web site has been optimized for SEO:
https://events.google.com/io2016/sitemap.xml
https://github.com/GoogleChrome/ioweb2016/blob/491d5f92629020b921739ea15a049606a8afacea/backend/handler.go#L213-L236
https://github.com/GoogleChrome/ioweb2016/blob/b1329e4bc1a4db3693845b9fc639b29806779d31/app/templates/layout_full.html#L226-L240
I think optimization does not fully cover individual events (the JSON-LD for selected event is not updated, etc), but it could be interesting to learn from team members how it worked in broader terms.

**Comment by ebidel** [comment]
We don't dynamically update the json-ld, but if you deep link to a session detail, the server will fll the values correctly: view-source:https://events.google.com/io2016/schedule?sid=15631cfd-0bef-e511-a517-00155d5066d7#day1/15631cfd-0bef-e511-a517-00155d5066d7

Make sure to cmd+shift+R that page (or open it in incognito), otherwise you'll get a service worker cached page.

**Comment by kanodia** [comment]
We have build a polymer app. It is a client side single page PWA. We use hasbank (#!) URL's to provide different content on it.

For example: 
www.domain.com/content/#!/content1
www.domain.com/content/#!/content2 and so on.

Now if each of this URL is indexed and crawled on Google, users can find my website with the keywords present in each hash banked url.

Now when I crawl my PWA, Google is only able to crawl the URL's.

I think it is because it is a client side app.

Now I really want to get my URL's on SEO.

How can I get it. What is the best way to get Google crawl your polymer PWA?

**Comment by kungufli** [comment]
@oneezy nope, unfortunately. I opened a request on the Google Webmaster Central Help Forum (https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/webmasters/TgaIYBOSseM/Iq0vu4HbBAAJ), if you can be interested, but as of now I'm still not getting the website corretcly indexed.

**Comment by arthurevans** [comment]
@kanodia I would avoid the hash bangs unless you're using the (deprecated) AJAX Crawling Spec (see https://developers.google.com/webmasters/ajax-crawling/docs/getting-started#overview-of-solution for an overview). This spec was created before the crawler ran javascript on pages, and it relies on your application providing a separate, server-rendered view of your page for the indexer. It doesn't sound like you're doing that, so the hashbangs are probably just confusing things.

The best thing for indexing is to have full URLs. (`www.example.com/path1`, _not_ fragments like `www.example.com/#!path1`). 

Make sure that each page has a unique title. For a SPA, you'll probably need to update this programmatically. For example, the doc site retrieves pages using AJAX, and updates the title when it loads a new page:

https://github.com/Polymer/docs/blob/master/app/elements/pw-shell.html#L281

**Comment by CaptainCodeman** [comment]
Cross-posted from https://github.com/PolymerElements/app-route/issues/119#issuecomment-229237012

I had a go at creating something to help with the SEO / meta-tag updating.

Here's what I came up with (any feedback appreciated):
https://github.com/CaptainCodeman/app-metadata

I tested it out by creating a test site:
http://app-metadata.appspot.com/

This has the metadata set from the element:

```
this.fire('app-metadata', {
  title: 'Why use Agile Project Management?',
  description: 'How Agile Project Management Methodologies help compared to the old Waterfall approach to Project Management',
  keywords: 'scrum, scrum master, agile, training, certification, professional, certified, CSM, PSM'
});
```

The content shows up in Webmaster Tools (using Fetch as Google) and the meta tags appear in the Google index:
https://www.google.ca/search?q=site:app-metadata.appspot.com

**Comment by kungufli** [comment]
For sure updating title and description is something that helps with SEO. 

Recently I also discovered another important factor for SPA. On my site I use the `neon-animated-pages` to switch from different content, but the content itself was all in the source page: I think that this create serious problem with indexing, because the Googlebot will crawl (and index) all the text content present in the page, even the hidden parts. Sure, the hidden content probably will get a much lower "score" in the index, but it's still there. So, in my case, what was happening is that when crawling different URLs (/home, /get, /download, /help, etc.) the bot was finding always the same content, even if different parts were hidden at different URLs. So Google considered all these urls as duplicates, I suppose, and selected only one URL to be shown in the search results (/help in this case, probably because this URL has more non-hidden content).

The solution to this SEO-messing SPA nightmare is to dynamically load the content, so when the crawler load a specific URL it will find only the relative content. I implemented this behavior by loading the elements that contain my pages at runtime with `Polymer.Base.importHref()`, instead of importing them in the html.
I'm still waiting for the Googlebot to find and organize all the content, but I already got, finally, the home page in the search results.
Hope this help.

**Comment by dypsilon** [comment]
@kungufli thank you for this report, please share any further findings.

How does the crawler actually find dynamically loaded pages (/get, /download, /help)? Do you use sitemap.xml or some tricks with the links and push state?

**Comment by oneezy** [comment]
@kungufli could you possibly post up your source code or example of this? 

Thankyou so much for helping spread the knowledge! As much as I love SPA's and PWA's, they are nothing without search.

**Comment by kungufli** [comment]
@dypsilon I actually have a sitemap but mainly for localitazion purpose. To make the crawler find the URLs I use the standard anchor HTML tag inside the `paper-button` I use to switch between the contents, like this:

```
<paper-button id="get">
    <a href="https://www.cerberusapp.com/get" onclick="return false;">Get</a>
</paper-button>
```

I set the `onclick="return false;"` to prevent the browser to actually load the link when you click on the button, since I want to manage this thing by javascript. Then I set a listener in the `paper-button` to do what I want:

```
document.querySelector('#get').addEventListener('click',
   function(e) {
      // load the correct page with importHref()
      // show the page on the neon-animated-pages
      // change the URL path in the browser for consistency with window.history.replaceState 
    });
```

@oneezy here is an example of dynamically loading elements in a `neon-animated-pages' pager: https://jsbin.com/vaqinatese/1/edit?html,output

**Comment by dypsilon** [comment]
@kungufli wow, thank you for this exhaustive answer. 

Do search engines look into the shadow DOM? In the example the "home-page" and "get-page" are components, which hide the content inside the shadow DOM. The question is whether search engines see it and if it brings any penalty.

**Comment by kungufli** [comment]
@dypsilon I can tell for sure that Google, Bing and Yahoo can see all the content in the shadow DOM, in fact it's was indexed on my site from all of them. I don't know if there is any penalty, but I don't think so.

**Comment by dypsilon** [comment]
@kungufli great, thank you!

**Comment by cthulchu** [comment]
@kungufli I can see that now your Cerberus website is indexed. I followed the thread on Google Central, but nothing interesting's there. 

I wondered what was the reason of not-indexing. It feels like the main reason was the onclick="return false". The mechanics of this tactics is a combo of .stopPropagatoin() and .preventDefault() from within jQuery It might've not been overridden by the polymer instruction in Google Bot's interpreter scope. Hence, the bot couldn't go to there and index the content properly.

Although I still see the return false in global menu.

Okay, what did you do to get all the pages indexed. 

And I really hope you didn't use the sitemap or other hacks since it's a cheat that doesn't bring any SEO value at all.

**Comment by kungufli** [comment]
@cthulchu Sorry for the big delay, the problem was not the `onclick="return false"` code, the site started to get correctly indexed after I changed the way the pages were loaded, as I described in a previous post: https://github.com/PolymerElements/polymer-starter-kit/issues/367#issuecomment-229293883

**Comment by alexandregiordanelli** [comment]
I changed my website to polymer and I am very upset.. Google cannot fetch data-binding from polymer.. I lost more than 1000 pages from google index and a lot of users.. 
https://enemresolvido.com

Case:
![captura de tela 2016-12-29 as 10 07 06](https://cloud.githubusercontent.com/assets/1518223/21543549/a3f3e708-cdae-11e6-86b8-2a1e232bea22.png)

https://enemresolvido.com/questoes/enem/167/um-garoto-foi-a-loja-comprar-um-estilingue-e-encontrou-dois-modelos-um-com-borracha-mais-dura-e-outro-com

**Comment by CaptainCodeman** [comment]
Seems to be indexed to me: https://www.google.ca/search?q=site%3Aenemresolvido.com&oq=site%3Aenemresolvido.com&aqs=chrome..69i57j69i58.1146j0j4&sourceid=chrome&ie=UTF-8#q=site:enemresolvido.com+um+estilingue+e+encontrou+dois

As with any major site revamp, it's well worth double checking what the impact on search ranking & indexability will be before going too far (ideally as a separate experiment, not on the live site).

My experience has been that sites using Polymer are indexed pretty well.

**Comment by alexandregiordanelli** [comment]
It was before changes to polymer.. The indexed page has a url different.. my new version using polymer is /questoes/enem/etc.. I dont recommend polymer.. I really commited a mistake to put on production.. Just another lesson learned..

**Comment by cthulchu** [comment]
Just test it before rolling out. Create a new page, implement polymer there, link to it and watch it. After this, start fixing your code until it's digestible by Google.

Polymer works great with Google. If you experience the opposite, you have issues with your code most likely.

**Comment by robdodson** [comment]
@alexandregiordanelli When did you make the change and launch into production? Indexing new urls can take time (days/weeks). I'm not an SEO expert but I believe if you change your URL structure there is a way to tell Search about the new URLs. Here are a couple resources I dug up.

https://support.google.com/webmasters/answer/6033049?hl=en
https://support.google.com/webmasters/answer/6065812?hl=en

It's been my experience that Search can handle sites built with Polymer. Our catalog is just one big element and its pages are indexed fine.

**Comment by alexandregiordanelli** [comment]
@robdodson It's an honor to be answered by you. I watched all your videos and read your tutors.. 
The search console "fetch as google" was not able to render because I have had a third party polymer element that has a small detail. 

In line 101 
https://github.com/dimitardanailov/polymer-mathjax/blob/master/elements/behaviours/MathJaxBehaviour.html

The problem is polymer doesnt show errors or warnings about that.. I changed it for myself and google can render.. When I committed an error like that, polymer build show me.. Navigators renders without problems but google not.. sorry for my english..

**Comment by robdodson** [comment]
Ah I see. Yeah, I wish Fetch As Google provided console output but I think the reason it doesn't is because you could use the console to gain knowledge about the search crawler and possibly hack it. That's just a guess though :)

**Comment by alexandregiordanelli** [comment]
Thats ok, right now.. Sadly we need to fetch errors from third elements.. 
test: function(arg){}    **!=**   test(arg){}

problems like that are common and no output errors..

![captura de tela 2017-01-03 as 16 26 40](https://cloud.githubusercontent.com/assets/1518223/21618320/7aa36b5e-d1d1-11e6-9d37-737425e7d61c.png)
https://enemresolvido.com/questoes/enem/167/um-garoto-foi-a-loja-comprar-um-estilingue-e-encontrou-dois-modelos-um-com-borracha-mais-dura-e-outro-com

**Comment by dtruffaut** [comment]
@robdodson I think what @alexandregiordanelli is trying say is : 

We need a way to log errors. Especially for third party web components, that we have not written ourselves and might be unreliable for whatever reason. 

A feature like a "big try / catch", but at the whole web component level. Something that is active at the rendering time, and if possible, something that is testable (Web Component Tester).

Example : "Looks like the webcomponent X produces errors and might not render as expected."

Then, if we have such a way to catch errors, we could use it in production and, once an error raises, we just have to log error + context to Big Query.

Some Polymer developers were formely server-side developers (PHP, Java...), that are used to log in production, an environment where you collect interesting and unexpected error cases.

**Comment by web-padawan** [comment]
@dtruffaut logging errors is reachable via some tracking systems. I don't think this is a think to implement in PSK. try / catch is usually not widely used because such constructions are not well-optimized AFAIK.

**Comment by alexandregiordanelli** [comment]
https://www.google.com.br/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:enemresolvido.com&start=70

A lot of page are indexed but breadcrumps/titles/descriptions and others important SEO things weren't indexed.. In my life, I've never have problems with google.. I think web components is a great technology, but we are living in the world that if you are not in google, you don't exist. 
I followed exactly as it was written on official tutos and apply html5push and replace states.. 
"Render" elements on server side always be the better option for SEO..  If google has problem with execute a lot of javascript, can you figure bing? 

It is my opinion.. you have my example..

**Comment by NaqashPixy** [comment]
@robdodson  same issue google is not indexing my site :(
https://polymerjs.io/
and on rendering it shows empty boxes 

Really worried its on 11th page on google :(

**Comment by CaptainCodeman** [comment]
For SEO you need to change the title and description metadata in the page as you navigate around. Google will pick these up and use them but by default it just sees what is in the index.html page which will be the same for every page. Fetch as Google in webmaster tools doesn't represent what the full bot will handle which seems to be a multi-phase system ... initial indexing of static content then more thorough indexing later.

@NaqashPixy You know your site is about 80Mb and keeps reloading a 56Mb video file? You might also want to avoid having spaces in URLs (they can work, but come with issues)

**Comment by NaqashPixy** [comment]
@CaptainCodeman  thanks for reply
i am changing title,description dynamically on page change
ok  i will change video and URLs , but don't think it will rank my site

**Comment by cthulchu** [comment]
@NaqashPixy put some unique mb even display:none text in the boxes, let Google index them, then search for the text with the site: operator to check if Google has it indexed.

But really I always try to fix JS to the point when I can see it executed in GWT. Just look at it. Usually it's easy to find a reason why something like phantomjs would not execute code.
