### ISSUE TITLE
Failed to print in Google chrome

### ISSUE THREAD

**Issue by boloson** [PolymerElements/polymer-starter-kit#376]
When I tried to print the page, it failed to generate a print preview in google chrome, where other browser generate the print preview properly.

**Comment by addyosmani** [comment]
Hmm. While Print support for PSK apps isn't something we've actively tested, I am curious why this is failing for us and not the Polymer docs site (it appears to be specific to PSK rather than Polymer).

![](http://i.imgur.com/965Du0O.png)

I've tried walking through the dependency tree in index.html disabling various pieces. At the moment the only thing that allows some amount of content to be rendered is getting rid of the `unresolved` attribute. This one will require some further investigation.

**Comment by gedw99** [comment]
fails for me on my polymer based project also...

**Comment by robdodson** [comment]
This looks like a general Polymer problem, not specific to PSK. https://github.com/Polymer/polymer/issues/2518

Would folks be ok with us closing the issue in this repo and directing everyone to https://github.com/Polymer/polymer/issues/2518?

**Comment by chuckh** [comment]
On Mac OS El Cap with Chrome 47.0.2526.106 (64-bit) I was able to get the below to print using Polymer Starter Kit by:

1. Go to http://polymerelements.github.io/polymer-starter-kit/
2. Do a Select All
3. Right clicking on page and selecting Print

It will only print what is visible on the screen and selected. 

![image](https://cloud.githubusercontent.com/assets/19915/12224892/5ddfc9d6-b7b0-11e5-910a-b7d2e2cb018f.png)
