### ISSUE TITLE
Vulcanize fail "Error in plugin "polyclean"

### ISSUE THREAD

**Issue by Dragod** [PolymerElements/polymer-starter-kit#391]
C:\gitrepos\my_app>gulp vulcanize
[11:30:32] Using gulpfile C:\gitrepos\my_app\gulpfile.js
[11:30:32] Starting 'vulcanize'...
[11:30:37] Error in plugin "polyclean"
Message:
    Unterminated string constant

**Comment by addyosmani** [comment]
Is this using a fresh pull of the latest PSK or did you make any changes to the codebase before trying to run `gulp vulcanize`?

**Comment by Dragod** [comment]
I did a fresh pull last night and havent change much, just few more html
file & js but didn't touch any of the build process. I can imclude the
gulp.js if that help
On 25 Sep 2015 13:34, "Addy Osmani" <notifications@github.com> wrote:
>
> Is this using a fresh pull of the latest PSK or did you make any changes
to the codebase before trying to run gulp vulcanize?

**Comment by addyosmani** [comment]
`polyclean` currently runs fine against the default version of PSK that we ship so it'll (most likely) be a specific change made to the HTML/JS files that are currently causing it to error out. Would it be possible to either:

1. Comment out your changes until you discover which one is breaking `polyclean` and report back
2. Share your HTML/JS changes so we can try to do 1. to figure out where the string constant is breaking

?

**Comment by Dragod** [comment]
I will comment/remove those file for testing anf I'll report back.

Anyway, here is my repo https://github.com/Dragod/itwebit_app, hope it help. Thanks.

**Comment by Dragod** [comment]
Commented out all my new js, html  import & still get "Unterminated string constant"

**Comment by addyosmani** [comment]
We recently switched back to not using `polybuild` and `polyclean` in PSK master and haven't been able to reproduce the issue you're seeing here. I'd recommend updating https://github.com/Dragod/itwebit_app/blob/master/gulpfile.js#L150 to https://github.com/PolymerElements/polymer-starter-kit/commit/cc5c192f413347800a729ea106fbfd3d6fad77dc (diff for the change). We'll try to dig into why this issue was happening upstream at polyclean otherwise.
