### ISSUE TITLE
ES6: Investigate "Ignoring duplicate element definition: undefined" warning

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/polymer-starter-kit#420]
This prints if you `gulp` and have followed the instructions at https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md.

See https://github.com/ebidel/polymer-experiments/issues/8#issuecomment-145625208 for more context. 

It's weird that `gulp` vulcanizes index.html, but the es6 stuff compiles + vulcanizes each element individually. It would be faster and produce less code output to compile + vulcanize either elements.html or index.html. Not both.

@nicolasgarnier this is also affecting your codelab: https://github.com/googlecodelabs/psk-es2015/issues/2

**Comment by nicolasgarnier** [comment]
Yes we're supposed to only vulcanize elements.html. Let me have a look.

**Comment by Nejat** [comment]
I get the same error with babel support, in addition i also get the following message

```
Error in plugin "polyclean"
Message:
    Unexpected token: punc ())

Process finished with exit code 1
```

I commented out the `my-greeting` and `my-list` imports in `element.html` the `Ignoring duplicate element definition: undefined` message disappeared, but the message above still appears

i started with `polymer-starter-kit 1.1.1`

i converted the following files to ES2015

`app\elements\my-greeting\my-greeting.html`
`app\elements\my-list\my-list.html`
`app\elements\routing.html`
`app\scripts\app.js`
`app\test\my-greeting-basic.html`
`app\test\my-listing-basic.html`

i had to change wct.conf.js to point to `dist` instead of `app` and injected the same dependencies of the `gulp serve` task to get the tests to work correctly

everything is in this fork of [polymer-starter-kit](https://github.com/Nejat/polymer-starter-kit)

**Comment by addyosmani** [comment]
@nicolasgarnier have you had a chance to chase this up?

**Comment by nicolasgarnier** [comment]
Having a look now!

**Comment by nicolasgarnier** [comment]
First, since we are not using polyclean anymore on master I've skipped investigating this. Let me know if you think I should still have a look (and perhaps file a separate bug).

Second, I believe there s a bug with Vulcanize. It seems it's not detecting the name of ES6-style elements (the `is` attribute) so it's thinking elements have an `undefined` name and therefore it prints the error message. For instance you can replicate this with the following minimal HTML file to vulcanize:

**my-element.html**
```html
<html>
<head>
  <link rel="import" href="bower_components/polymer/polymer.html">
</head>
<body>
<dom-module id="my-element">
  <template>
    <div>Hello World</div>
  </template>

</dom-module>
<script>
  class MyElement {
    beforeRegister() {
      this.is = 'my-element';
    }
  }
  Polymer(MyElement);

  class MyElement2 {
    beforeRegister() {
      this.is = 'my-element-2';
    }
  }
  Polymer(MyElement2);

  class MyElement3 {
    beforeRegister() {
      this.is = 'my-element-3';
    }
  }
  Polymer(MyElement3);
</script>
</body>
</html>
```

Try vulcanizing the following with `vulcanize my-element.html > /dev/null` and you'll get the following output on the console:

```bash
Ignoring duplicate element definition: undefined
Ignoring duplicate element definition: undefined
```

**Comment by nicolasgarnier** [comment]
re-assigning to @ebidel so he can follow-up with the vulcanize folks about that.

**Comment by ebidel** [comment]
Please just file a bug on that project.

**Comment by nicolasgarnier** [comment]
NP. Also I'll hav a look at the tests failures on the bug that @Nejat just filed: https://github.com/PolymerElements/polymer-starter-kit/issues/433

**Comment by nicolasgarnier** [comment]
Filed upstream: https://github.com/Polymer/vulcanize/issues/263

**Comment by robdodson** [comment]
Closing as this looks like a vulcanize bug not specific to PSK
