### ISSUE TITLE
ES6/ES2015 & WCT: tests are failing with babel recipe 

### ISSUE THREAD

**Issue by Nejat** [PolymerElements/polymer-starter-kit#433]
starting with `polymer-starter-kit 1.1.1` as my base, I followed the directions in [Add ES2015 Support Babel](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md) and then I converted the following files to ES2015

```
app\elements\my-greeting\my-greeting.html
app\elements\my-list\my-list.html
app\elements\routing.html
app\scripts\app.js
app\test\my-greeting-basic.html
app\test\my-listing-basic.html
```

This caused the tests to fail, even though `gulp serve` was working correctly.

To get all of the tests working correctly, I had to change `wct.conf.js` to point to `dist\test` instead of `app\test` and injected the same dependencies of the `gulp serve` task.

everything is in this fork of [polymer-starter-kit](https://github.com/Nejat/polymer-starter-kit)

**Comment by nicolasgarnier** [comment]
Thanks for this @Nejat. It seems compiling the tests was overlooked in the ES6 recipe.

However my opinion is that tests should always be ran on `/dist` rather than on `/app` anyways. Do you agree @addyosmani ? As we should be testing close to what will be deployed on prod.

Basically we have 2 ways of "fixing" this: I can:
 - Add steps to the ES6 recipe so that tests are ran from `/dist` instead of currently `/app` and make sure gulp build tasks are ran before running the tests.
 - Add this directly to master since (IMO) it;s good practice to run tests on `/build` and it does not depend on wether the users uses ES6 or not.

_______

For reference @Nejat fix is:

In **wtc.conf.js** replace `'suites': ['app/test'],` by:
```js
  'suites': ['dist/test'],
```

in **gulpfile.js** add the following lines:
```js
var injectDependencies = function (task, dependencies) {

  if (task !== null) {
    dependencies.forEach(function (dependency) {
      task.dep.push(dependency);
    });
  }
};

var wctTestDependencies = gulp.tasks.serve.dep;

gulp.task('wct:local')

injectDependencies(gulp.tasks[ 'wct:local' ], wctTestDependencies);
injectDependencies(gulp.tasks[ 'wct:sauce' ], wctTestDependencies);
```

**Comment by Nejat** [comment]
two things:

* the above solution also requires the `bower_components` path mapping to point to `dist` as well

* I personally like how `WTC` currently doesn't require a build, making element development more fluid and dynamic by being completely isolated. Maybe `WCT` can inject [Babel Browser Support](https://babeljs.io/docs/usage/browser/) for the ES6 recipe. 

I agree all final testing should be done on `/build`. 

How about two testing options? 
* Tests for element development 
* Tests on `\build`.

**Comment by nicolasgarnier** [comment]
> * the above solution also requires the `bower_components` path mapping to point to `dist` as well

Good catch. I updated by post above.
