### ISSUE TITLE
Host on gh-pages and add demo link in documentation

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/polymer-starter-kit#459]
We should keep http://polymerelements.github.io/polymer-starter-kit/ up to date and publicize it on the doc site

**Comment by chuckh** [comment]
I agree. Do you think we should keep it up to date with the latest release
or master?

On Fri, Oct 23, 2015 at 12:53 PM, Eric Bidelman <notifications@github.com>
wrote:

> We should keep http://polymerelements.github.io/polymer-starter-kit/ up
> to date and publicize it on the doc site
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PolymerElements/polymer-starter-kit/issues/459>.
>



-- 
Chuck Horton
proplanr.com
www.hware.com
chuck@hware.com
www.twitter.com/chuckhorton
530.268.5840

Let us create a world that works for all.

**Comment by VikramTiwari** [comment]
Hey @ebidel this (https://github.com/PolymerElements/polymer-starter-kit/pull/472) should do it.

**Comment by chuckh** [comment]
I have tested this method and successfully deployed PSK at http://proplanr.github.io/polymer-starter-kit. But routing does not work correctly. I found the following:

1. http://proplanr.github.io/polymer-starter-kit gets redirected to  http://proplanr.github.io
2. Tapping on Home, Users, or Contacts works but shows `http://proplanr.github.io/#!/users` instead of `http://proplanr.github.io//polymer-starter-kit#!/users` for example. Also if you refresh page these urls don't work.
3. Favicon does not work

Tried page.js 1.6.4 and master branch does not fix routing.

Tried `page.base(window.location.pathname.replace(/\/$/, ''));` and `page.base('/polymer-starter-kit');` got these results:

1. http://proplanr.github.io/polymer-starter-kit works with no redirect
2. Tapping on Home, Users or Contacts gets 404 shows `http://proplanr.github.io/users` instead of `http://proplanr.github.io//polymer-starter-kit#!/users` for example 
3. Favicon does not work

We will need to address the routing issues to successfully deploy to Github pages. See issue #320 for more about this problem.

**Comment by chuckh** [comment]
I got Github pages hosting to work including routing for PSK. You can see it at http://proplanr.github.io/polymer-starter-kit/.  You can see the changes at https://github.com/proplanr/polymer-starter-kit/commit/90bb19cb85f5b9f9dca4f136fe4e6f9588867c54.  I did the following to make it work:

### Deploy
1. Added gulp-gh-pages and dependency
2. Created deploy-gh-pages and build-deploy-gh-pages gulp tasks
3. Added `. publish/` to .gitingore

### Routing
1. Set page.base using `window.location.pathname.replace(/\/$/, '')`
2. Added app.baseUrl for base pathname
3. Added app.baseUrl route
4. Removed all `/` from data-route
5. Added app.getUrl function to add pathname to links

### Misc
1. Added `<link rel="shortcut icon" href="/polymer-starter-kit/favicon.ico"/>` with comments
2. Added demo link to readme.md

@addyosmani @samccone should I make a pull request for PSK repository to make these changes?

**Comment by addyosmani** [comment]
Thanks for spending time working on getting this cleaning working @chuckh. With respect to the routing changes, do the modifications listed:

* Still work fine when testing the project locally during `gulp serve`
* Require significant change for users not deploying to gh-pages?

Imo, I think we should either add to #472 or create a fresh PR with the extra changes here as this is a far more comprehensive take on the problem. My personal preference is fresh PR.

**Comment by chuckh** [comment]
> * Still work fine when testing the project locally during gulp serv ***YES***, see test results below.

> * Require significant change for users not deploying to gh-pages?  ***NO***

Only change is to change one line in app.js from: 
`app.baseUrl = '/polymer-starter-kit/';` to `app.baseUrl = '/';`

See line at:
https://github.com/proplanr/polymer-starter-kit/blob/add-gh-pages-deploy-routing/app/scripts/app.js#L80


Test results:
![image](https://cloud.githubusercontent.com/assets/19915/10945634/2ea4ff90-82d3-11e5-9d28-6e092b5d189d.png)

See latest diff at https://github.com/PolymerElements/polymer-starter-kit/compare/master...proplanr:add-gh-pages-deploy-routing

See on latest on github pages:
http://proplanr.github.io/polymer-starter-kit

I also deployed to Firebase at
https://polymer-starter-kit.firebaseapp.com
￼
I can create a new PR for all these changes.

**Comment by abdonrd** [comment]
Thanks for the work, @chuckh, it´s awesome! :star:

**Comment by chuckh** [comment]
I created pull request #481 for Github Pages deploying and routing.

**Comment by samccone** [comment]
landed :)
https://github.com/PolymerElements/polymer-starter-kit/commit/7082366bc258ae748837d3adfe754e70955180f9
