### ISSUE TITLE
Gulp html task not minifying

### ISSUE THREAD

**Issue by MartinsThiago** [PolymerElements/polymer-starter-kit#467]
I realized that html task is not minifying our final index.html, would it be propositional?

**Comment by samccone** [comment]
What do you mean by `propositional`?>

**Comment by MartinsThiago** [comment]
Sorry I mean `purposeful`

**Comment by MartinsThiago** [comment]
in the end... other resources get minified... but not on `/index.html` which most part of the code is located

**Comment by moderndeveloperllc** [comment]
@MartinsThiago Are you putting most of your elements into the index.html instead of the elements/elements.html? I just put in a PR that got merged - #486 - that minifies the CSS and JS of elements.vulcanized.html. The latest master/ I'm using of the gulpfile does minimize the index.html file, but if you are putting all your elements there, the CSS and JS of the vulcanized files wouldn't be.

**Comment by MartinsThiago** [comment]
@moderndeveloperllc I'll try to update my gulpfile... but I am placing my elements into `elements/elements.html` I saw that javascript and even css got minified... but html just got concatenated

**Comment by lepatlamass** [comment]
hello if i don't install all the dependencies will it affect my work doing production??

**Comment by addyosmani** [comment]
If you don't install all dependencies you won't have access to the production tooling we include out of the box. Are you having issues with any deps in particular?

**Comment by lepatlamass** [comment]
yes can't install gulp serve

**Comment by robdodson** [comment]
Running `gulp` should produce a minified `index.html` in the `dist` directory. I believe the elements that are going through vulcanize are not being minified because we've had all sorts of issues with minifiers not playing nice with vulcanized output. https://github.com/polymer/vulcanize#what-happened-to-feature-from-0x It seems like every time we introduce a minifier into the mix it produces subtle and annoying to track down bugs.
