### ISSUE TITLE
I get Polymer not defined when following the codelab steps: "Build an ES2015/ES6 app with the Polymer Starter Kit"

### ISSUE THREAD

**Issue by damibarbieri** [PolymerElements/polymer-starter-kit#510]
Hi! This is my first attempt to work with the PSK and I'm getting:
Uncaught ReferenceError: Polymer is not defined(anonymous function) for the custom elements that come already develop and with the one that I'm creating by following the codelab steps. I'm sure that it is related on the bower_components imports the polymer.html file as per my short experience with Polymer. However, I don't know how to check this as gulp is serving and building the source files.

**Comment by robdodson** [comment]
Are there errors in the console? Is there a 404 for polymer.html in the network panel?

**Comment by damibarbieri** [comment]
@robdodson just updated the main comment!

**Comment by samccone** [comment]
(going to close as a non-issue with PSK) and rather a debug request, feel free to continue the debugging here :dancer:

**Comment by robdodson** [comment]
@damibarbieri using PSK you'll want to run `gulp serve` to test. You should then be able to look in the Network panel to see if there are any 404s.

**Comment by damibarbieri** [comment]
@robdodson I have only a 404, but I don't think that is a big issue. The main problem is that I get that the Polymer function is not defined for all the custom elements.
![image](https://cloud.githubusercontent.com/assets/5324713/11191749/bb7f022e-8c7b-11e5-9964-d5ac9d02e629.png)

**Comment by robdodson** [comment]
It's probably because Polymer is not being imported. Can you verify in your
network panel that you see polymer.html

**Comment by bennettrogers** [comment]
I'm getting the same result. I'm also new to Polymer. I could be way off, but could this be a result of crisper ripping the inline script into its own file which doesn't know how to find the Polymer class? I copied the gulp 'js' task straight from the v1.1.1 ES2015 docs (which aren't entirely accurate since the 'html' task  has already been updated to call `optimizeHtmlTask`, but the docs don't reflect that yet).
![screen shot 2015-11-16 at 10 02 04 pm](https://cloud.githubusercontent.com/assets/933251/11203976/959df83e-8cae-11e5-82ee-830a6150d372.png)

**Comment by samccone** [comment]
I debugged this tonight and you can fix it by adding a polymer import to your elements.html file ... However I am sure this is not the best fix...

**Comment by bennettrogers** [comment]
For reference, [here's](https://gist.github.com/bennettrogers/d0e795d3b83a5852ab78) the gulpfile I ended up using. I had to mix and match steps from the PSK v1.1.1 and v1.2.0-rc.1 ES2015 docs. Something in here might be part of the problem, I'm not sure yet.

**Comment by damibarbieri** [comment]
I moved to PSK v1.1.1 and I didn't experience this issue again. However, it seems that the problem is related to gulp. The way it separates and order the js files for each elements seems to be wrong.
![image](https://cloud.githubusercontent.com/assets/5324713/11211469/6f66273a-8d0e-11e5-843e-8d1772aa44fe.png)
As the js files are all placed in the script folder. But, IMO they should be placed with their respective html file to prevent this issue from happening.
![image](https://cloud.githubusercontent.com/assets/5324713/11211508/a4abcb3e-8d0e-11e5-847e-118d1d63d88d.png)

**Comment by damibarbieri** [comment]
@bennettrogers I tried with your gulpfile, but I had the same results. However, yesterday I tried using PSK v1.1.1 and it started working and today I did a gulp serve again with the same results :sob:

**Comment by alobaidi** [comment]
Hi,
i have the same Problem. i followed the instructions on this page https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md. But still get "Polymer undefined". 
In the Browser Network i can see the polymer.html loaded.

Is there any Idea where the problem might be?

thanks

**Comment by samccone** [comment]
cc @robdodson @arthurevans  do you know who to ping about updating this codelab?

**Comment by robdodson** [comment]
Hmmm I *think* @nicolasgarnier was the original author? Apologies if I'm mistaken :)

**Comment by andischerer** [comment]
I've run into the same Problem. Could be an async script loading issue.
Adjusting my `js` gulp task:
```js
.pipe($.if('*.html', $.crisper({
	scriptInHead: false
})))
```
fixed it for me.

**Comment by addyosmani** [comment]
cc @nicolasgarnier as he was the one that authored this codelab.

**Comment by nicolasgarnier** [comment]
Guys could you let me know if, to do the codelab, you downloaded PSK's `master`, PSK `1.2` or, [as the per the codelab's instructions](https://www.code-labs.io/codelabs/polymer-es2015/#1),  PSK `1.1.0`? (which is an older version)

The thing is that editing the codelab is a manual process and it's a bit challenging to keep it updated with all latest changes immediately. And I was thinking relying on a stable release instead of `master` as a best practice.

I was planning to wait for PSK `1.2` to be released before updating the Codelab, it's been out for 5 days now so I can now go ahead and do that. But I'm a little worried that the next time we update the gulp file we'll have discrepancies with `master` again and the same thing will happen (if developers prefer using `master`). FYI I skipped PSK `1.1.1` since there was [an issue with Polyclean](https://github.com/PolymerElements/polymer-starter-kit/issues/369#issuecomment-149850538) which was removed from master anyways so we never fixed it.

Proposal: I could change the codelab so that it is based on `master` and therefore doesn't require an update for each stable version:
 - Tell developers to download PSK from `master` instead of a stable release on Step 2.
 - Remove [Step 3 of the codelab](https://www.code-labs.io/codelabs/polymer-es2015/#2) and replace it with a reference to [the ES6 recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md) which the codelab is based on and which we keep updated with `master`.
This way we can keep the changes upstream and the codelab should always be fine.

Thoughts? Basically should we only keep updating the codelab for each stable release (with some potential lag or even versions skipped...)? Or point to `master` as per the above?

**Comment by samccone** [comment]
I was wondering if it might be possible at the start of the codelab to tell someone to run git clone <repo>@TAG

and then problem fixed? But if you tell people already to download 1.1 and they are not doing that... then perhaps there might be a UX problem with that step

**Comment by nicolasgarnier** [comment]
The UI it seemed OK to me: 

![image](https://cloud.githubusercontent.com/assets/3766663/11477681/691d4f18-9789-11e5-8fe5-a3c1c7211509.png)

https://www.code-labs.io/codelabs/polymer-es2015/#1

My guess is that developers want the latest and greatest anyways.

**Comment by samccone** [comment]
that button does seem like it is pretty clear, however I helped several people IRL running into this exact issue the other week

open to any ideas people have :)

**Comment by robdodson** [comment]
I vote for removing the button and replacing with a `git clone` command.

**Comment by addyosmani** [comment]
> I vote for removing the button and replacing with a `git clone` command.

:+1:

**Comment by arthurevans** [comment]
`git clone` command may be more error-free (at least for folks using CDE). I'd also recommend a troubleshooting step at the end of the relevant section (wherever people usually encounter this error) telling people to make sure they downloaded the correct version.

**Comment by JustinXinLiu** [comment]
Thanks @andischerer that change fixed the problem!

**Comment by OmriAharon** [comment]
@andischerer  You sir, deserve a beer! Your solution did the trick for me.

**Comment by robdodson** [comment]
I believe the recipe includes the line about `scriptInHead: false` already, doesn't it?

**Comment by OmriAharon** [comment]
@robdodson  Perhaps I downloaded something I shouldn't have? I followed the tutorial and downloaded from the green button here: https://codelabs.developers.google.com/codelabs/polymer-es2015/#2

Then it says to add the 'js' task to the gulpfile, in which it's written as `.pipe($.if('*.html', $.crisper()))`

**Comment by robdodson** [comment]
@OmriAharon ah! the code lab needs to be updated. We have a separate guide in the Polymer Starter Kit repo https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md

**Comment by robdodson** [comment]
@nicolasgarnier would you mind updating the code lab doc with this change?

**Comment by OmriAharon** [comment]
@robdodson  Thank you :)
