### ISSUE TITLE
Dependencies deprecated 

### ISSUE THREAD

**Issue by stefanoantonel** [PolymerElements/polymer-starter-kit#540]
Hello team (this is my fist time I'm trying to use the Issues section in github and I want to report a warning that I've got) 
In the npm install process some depencencies are deprecated 

> npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
 
Please let me know if this issue is correct to be published or I don't have to submit these kind of things.
Thank you so much for the hard work!

**Comment by samccone** [comment]
Hi @stefanoantonel :wave: thanks for the report, since we do not have lodash as a direct dependency https://github.com/PolymerElements/polymer-starter-kit/blob/master/package.json, this error is from one of our child dependencies, your best bet here is to track down which package is using the old version and open up a bug in that repo.

Thanks again for the issue! Let us know if you have any questions.
