### ISSUE TITLE
How does routing.html have access to var app set in scripts/app.js?

### ISSUE THREAD

**Issue by alexkolson** [PolymerElements/polymer-starter-kit#630]
Somehow routing.html seems to be able to access `app` that is set in scripts/app.js:
```js
var app = document.querySelector('#app');
```
How come this works? How does routing.html find the `app` variable?

**Comment by robdodson** [comment]
The app variable is made into a global because it's not enclosed in a function. The setup is not great because it relies on the fact that the `WebComponentsReady` handler in routing.html will fire after `app` has been created. If you remove the web components polyfills this actually breaks. It would probably be better to avoid the race condition and setup the routing after `app` has been defined

**Comment by alexkolson** [comment]
Thanks @robdodson! Answers my question. :+1:
