### ISSUE TITLE
V(n) goal posts 

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#653]
#### Below is a brief list of high level goals that I would like to really nail with the v(n) release :sparkles: 

* [x] Well defined (file directory) structure for components and apps
* [ ] Generator to quickly add new components and pages
* [x] Rock solid baked in router solution
* [ ] A Simple Unit testing approach (mocha / ava)
* [x] **An** opinionated build tool*
* [ ] Import / require javascript everywhere / anywhere
* [ ] State management --- redux wrapper? immutable js? -- we need page level and view level state management that just works 
* [ ] Simple deployment -- https://github.com/carrot/ship <--- or something like it

**Comment by robdodson** [comment]
cc @tjsavage

**Comment by abdonrd** [comment]
Sounds great! :grin:

**Comment by addyosmani** [comment]
Thanks for sharing this list, @samccone! We have a week of Polymer planning for this quarter lined up and it would be great to look at how we can tackle some of these items as part of our high-level goals. I'd love to see us rewriting PSK for more flexible layout (app-layout elements), the new router (carbon-router) and what we can do to both simplify our tooling (before we add in more) and lower friction for progressive web apps.

> Generator for quickly adding new components and pages

We've been kicking around an idea for maybe doing a polymer-cli. This could be something that abstracts away the Yeoman generator but adds in support for polylint, polyclean and so on without you having to mentally reason what to use. It'll be interesting to hear what you and the rest of the team think of going in that direction.

> An opinionated build tool

What does this mean? :) My experience with polybuild (which may be what you're alluding to) tells me that it can be hard for us to ship something that caters for the numerous configurations folks want us to support, but that doesn't mean we shouldn't do it better. Will wait for you to expand on this.

> State management

Imo, it would be good to bring this up with the team to see if there's a Polymer-world view on state management that could be built or adopted. Remember that we'll also be trying to reduce the complexity overhead of using PSK and opting for Redux or an immutability library may mean we expect folks to learn how those work before they can really take advantage. Not at all saying no, simply saying we should keep that in mind.


> Import/require JavaScript everywhere

It would be useful to look at the tooling pipeline for what folks would expect here. Babel support everywhere + ES2015 linting (?) + anything else? It would be good to learn from the issues we ran into with support for ES2015 in current PSK. Are you also asking for CJS require support?

> Deployment

I'm +1 for deployment.

**Comment by chuckh** [comment]
:+1:  for @samccone  list.

It would also be great to have options to add a  landing page, login form and signup form.

**Comment by chuckh** [comment]
I created a possible use case spreadsheet for PSK v2, to view and comment go to:

https://docs.google.com/spreadsheets/d/1SJyDYQDcXJUvc2kkHshBJo4255HoZSLDBiiwIDxB2N8/edit?pref=2&pli=1#gid=0

**Comment by chuckh** [comment]
We should consider `globals` and `app layout options` too.

**Comment by nidelson** [comment]
@chuckh When you say login and signup form... refers to authentication and authorization? Intercept router and everything? Oh yes!
When speaking web application, progressive web application, it is inevitable not touch on these issues.

**Comment by vinerz** [comment]
Didn't know that YouTube gaming was made with Polymer! That's some great news for me.

**Comment by joryphillips** [comment]
Would it be possible or realistic for 2.0 to reduce the # of tools used in the install/build process? i.e. narrow down to just npm and gulp?

**Comment by samccone** [comment]
@joryphillips we are actively investigating just that :)

**Comment by cnbuff410** [comment]
I'm curious on why PSK doesn't use Polybuild replace a bunch of current tool? Is it due to the immature state Polybuild is currently in?

**Comment by ZergMark** [comment]
@cnbuff410 They tried to use Polybuild a couple of months ago and ran into too many issues.

**Comment by David-Mulder** [comment]
Isn't it time to start thinking about HTTP/2 either way? I mean, right now 83% of Polymer supported browser usage supports HTTP/2, add to that that PSK v2.0 isn't out for a while longer we can easily assume that by that time we're talking about 90% or more. Advantages of HTTP/2 include a greatly simplified (or even entirely abandoned) build process and extremely simple dynamic loading, both things that I think would be very valuable for this repo. Either way, did a write up about getting PSK (+ a backend API) up and running on HTTP/2 [over here](http://blog.apriol.com/2016/01/http2.html).

**Comment by chuckh** [comment]
I created the rough spreadsheet to show possible use cases with features that would be required to build them. I categorized the PSK Use Cases into Public: for sites that don't need login and signup abilities, Secure: sites that need to be logged into to access content (invite only), Commercial App: sites that need to provide new user signup and existing user login abilities.  This was just a first pass. I am open to any suggests on how to change it or scrap it all together. 

### PSK Version 2 Use Cases Spreadsheet:
https://docs.google.com/spreadsheets/d/1SJyDYQDcXJUvc2kkHshBJo4255HoZSLDBiiwIDxB2N8/edit?pref=2&pli=1#gid=0

**Comment by abdonrd** [comment]
For linting, I think that we can use **eslint**.

[Polymer/polymer](https://github.com/Polymer/polymer) will begin to use it: https://github.com/Polymer/polymer/pull/3382

**Comment by alexpaluzzi** [comment]
"Import / require javascript everywhere / anywhere"

Can I get some clarity on this one? Are we talking using a module loader to imperatively import Polymer elements? If I could build Polymer elements in JS files (without feeling like I'm hacking it up too much), my love for Polymer would grow immensely. And I'm already infatuated with it.

**Comment by robdodson** [comment]
@alexpaluzzi kind of. Our thinking was to add the ability to import/require modules inside of your HTML Imports.

**Comment by alexpaluzzi** [comment]
@robdodson ah. That's pretty exciting. I know there is talk about unifying the ES2017 (or whatever it's called) module loaders with HTMLImports to use the same mechanism underneath.

I envision a future where we can export Polymer elements out of JS (or HTML) files, and then require them in other JS files (or import them in HTML files, like today). I haven't dove into the internals of HIs, but I'm just daydreaming here.

**Comment by robdodson** [comment]
yeah that's kind of where we're headed. We want to make sure you can pull in external js modules and use them in your elements and down the line possibly export things but that particular bit is still being heavily worked out by the standards folks

**Comment by TimvdLippe** [comment]
For our site we use polybuild and we have not encountered any problems with it. It would be nice to reconsider adding polybuild to the build chain. The minification and splitting of HTML and JS is a nice win.

**Comment by joryphillips** [comment]
Question: Is there a reason everything is **px**- based instead of **em**?

**Comment by samccone** [comment]
yep we can switch :+1:

**Comment by robdodson** [comment]
@joryphillips @samccone personally I feel that px is a lot easier to reason about. I know the argument for em being great for responsive design but... :(  For responsive stuff I'd rather work off of default units in custom properties if possible:

ex:

```
:root {
  --gutter: 4px;
}

section {
  margin: var(--gutter);
}

@media (min-width: 600px) {
  :root {
    --gutter: 16px;
  }
}
```

Here's a full blown example: https://googlechrome.github.io/samples/css-custom-properties/index.html

**Comment by vguillou** [comment]
Here is short list of :+1: and other things that I think a starter kit could integrate:

- I think I've read (somewhere) that `app-layout` and the switch to an 'app-element' design are being considered: If so :tada:  

- Remove the page's content from `index.html` and create page elements. I assume this is implied by the `Generator to quickly add new components and pages` item so :+1: for that as well.
More advanced topics require it (unit testing, on-demand page loading, advanced page transitions,...) and it also won't hurt the `Well defined (file directory) structure for components and apps`.

- Consider implementing the best performance practices by default, not in a recipe (at least conditionnaly load the polyfill and FOUC prevention with a splash or an app skeleton)
Why: Everybody wants minimal network overhead and a fast first paint. In the current state of PSK this is typically something that can be intimidating for newcomers to understand and execute. But it should get significantly easier to implement if the PSK switches to an 'app-element' design (notably kickstarting the app logic in JS will be easier than now), so why not make it default? Not to mention that this will obviously get more and more valuable as the web-components specification makes progress and the browser support grows.

- Fix the blank/broken page situation in unsupported browsers or when JS is disabled? (could be as simple as a noscript tag + browser-update.org?)

Willing to help making any of this happen.

**Comment by TimvdLippe** [comment]
I really like the idea of page elements, especially as the recently released carbon route can be nicely integrated with the different pages. This would solve issues/eases development for subpages like the current user pages.

**Comment by abdonrd** [comment]
`app-shell` + `app-layout` + `carbon-route` + one element for each page sounds really awesome! :tada:

**Comment by timeu** [comment]
+1 for state-management (specifically redux)
I started a project based on the PSK and as the app grew I had a really hard time copying with state-management/updates (basically passing slices of a global state around the component tree and mutating it). I recently added support for redux using the [polymer-redux](https://github.com/tur-nr/polymer-redux) element/behavior and so far it has been great. 

For React it is recommended to split up the components in [Presentational and Container components](http://redux.js.org/docs/basics/UsageWithReact.html). The same thing can also be done with Polymer elements (Container elements implement the redux behavior and can bind properties to specific store slices) and Presentational components are completely unaware of redux. 
This really simplifies state-management a lot. Without the redux aware Container components one has to pass data down the entire component graph. 
There are also nice benefits of using redux: The Redux Chrome Dev tools allow for time travel debugging, unit tests of reducers are trivial and for side effect and asynchronous calls one can use the great [saga-redux](https://github.com/yelouafi/redux-saga) library that uses generators under the hood (thus making unit testing trivial again). 

So for me Redux and Polymer have been a really great mix. I am not sure if the PSK needs actually to incorporate Redux itself but at least one could create a recipe and some best practices (I can help with that if needed). 
One thing I would wish for v2 tough, would be to incorporate a module bundler (such as webpack, rollup, etc) or at least make it easy to add one (I tried and somehow failed :-(). Redux would benefit of it because at least with webpack one can do hot-reloading of reducers and also have a more sane structure for the various scripts (reducers, action creators, effects) using ES6 module export/import directives.

Sorry that the post got so long ;-)

**Comment by robdodson** [comment]
Thanks for sharing the polymer-redux component @timeu. I hadn't seen that yet (though I am familiar with Redux). It's great to see folks combining it with Polymer

**Comment by timeu** [comment]
@robdodson: no problem, hope it might be useful for some others. 
Polymer-redux is really super simple (it's basically just a Behavior and does what `connect` and `mapStateToProps` do in the react-redux world). 
The cool thing about combing Polymer with Redux is that Polymer's data-binding and specifically the computed properties provide the same functionality that [reselect](https://github.com/reactjs/reselect) provides out of the box (using memoiziation to avoid unnecessary recalculations).

**Comment by abdonrd** [comment]
I'm thinking that it would also be interesting to have multilanguage.

**Comment by felixzapata** [comment]
I´m agree with @abdonrd

**Comment by moderndeveloperllc** [comment]
@abdonrd @felixzapata I would think that multilocale functionality would be beyond the scope of this starter kit. There are a few components that provide this functionality though: https://customelements.io/search/translate

**Comment by robdodson** [comment]
The Polymer team is exploring creating elements to support
internationalization but I don't think we'll roll it into the PSK starter.
Our goal is to actually reduce the amount of stuff in PSK to make it a more
general purpose starting point for folks. Then we plan to build sample apps
that demonstrate using different things like internationalization.

**Comment by dandv** [comment]
@joryphillips re.

> Would it be possible or realistic for 2.0 to reduce the # of tools used in the install/build process? i.e. narrow down to just npm and gulp?

You may want to :+1: #728.

**Comment by robdodson** [comment]
@dandv no need to +1 that issue. The Polymer team wants to move off of bower. The difficulty is in the fact that npm doesn't currently offer a good way to handle version conflicts when it tries to flatten its tree of dependencies. For most javascript libraries this isn't an issue, but it's a problem in our case because you can only have 1 version of a tag registered at a time. It means we will have to build a conflict resolution, deduplication tool that runs after npm install and it's not something we've had a chance to tackle yet. I think we'd prefer if npm did this instead of us :P

Regarding reducing the number of tools, that's what https://github.com/Polymer/polytool aims to do.

**Comment by robdodson** [comment]
OK I'm going to close this and try to detail all the points that I think we've addressed:

> - Well defined (file directory) structure for components and apps

We're now using the structure advised by Polymer CLI

> - Generator to quickly add new components and pages

This is a feature the CLI team is working on

> - Rock solid baked in router solution

We're now using [app-route](https://github.com/PolymerElements/app-route)

> - A Simple Unit testing approach (mocha / ava)

We have web-component-tester with mocha already set up. That should be enough to get folks rolling

> - An opinionated build tool*

Polymer CLI

> - Import / require javascript everywhere / anywhere

This one's a little tricky. Polymer itself is migrating toward ES2015 and so classes and ES syntax should be solved naturally quite soon. However we're still relying on HTML Imports as 1. modules continue to be sorted out and 2. we don't want to force folks to use an additional tool just to play with Polymer. Having said that, I think the team will be releasing guidance on how to import Polymer using a tool like System.js but we should wait on them to roll that out versus trying to solve it ourselves in PSK. As we saw with ES2015 support in previous versions of PSK, it lead to a boatload of errors when we tried to work around lack of official support in the library.

> - State management --- redux wrapper? immutable js? -- we need page level and view level state management that just works

I think we'll have more to show here in the near future. Stay tuned.

> - Simple deployment -- https://github.com/carrot/ship <--- or something like it

I think because we're trying to keep PSK as simple as possible we might omit this step and instead roll it into a separate generator (or come up with a guide on using ship).
