### ISSUE TITLE
feedback on PSK perf doc

### ISSUE THREAD

**Issue by mdagit** [PolymerElements/polymer-starter-kit#698]
(Please take a look at issues #313 and #357 which were prior discussion).

There are a few things I still don't understand after reading the github issues #313 and #357 and the perf doc polymer-perf.md :

1. Presumably webcomponents-lite.js detects when the browser it is loading into already has a
native implementation, and it just short-circuits? Why not have that feature probing right
at the top of webcomponents-lite.js itself? Or at least support that ability with one of the
url flags? Then worst case it is just the overhead of loading the compressed js file, which isn't that bad.

2. The perf whole discussion seems to conflate two separate issues: 
    A. Avoid webcomponents-lite.js when running in a browser that doesn't need it.
    B. Avoid the FOUC and unresponsive feeling by being more async.

For 2A, as I said, why not build that in to the lite js? Or consider a compromise solution where 
the dynamic script element for just the webcomponents-lite.js is done in <head> sync,
and everything else is async? Then it simplifies the approach.

For 2B, I think it needs to be said up front that none of the described changes actually make the
application truly interactive any sooner. It just an illusion to the user. To *actually* make the first
page more interactive sooner would require optimization tools that (AFAIK) don't exist for Polymer --
dead code analyzer to guide vulcanize, or the ability to identify a bundle of components as critical
and one ore more others as something to be async, etc. Waiting even 2 seconds for a page is
just too long.

**Comment by robdodson** [comment]
> Presumably webcomponents-lite.js detects when the browser it is loading into already has a
native implementation, and it just short-circuits? Why not have that feature probing right
at the top of webcomponents-lite.js itself? Or at least support that ability with one of the
url flags? Then worst case it is just the overhead of loading the compressed js file, which isn't that bad.

Some folks would consider that overhead bad. Although the polyfills are quite small (11kb gzipped), it's cheaper to just have a few lines of inline script vs. incur the additional HTTP request to pull that file down.

> For 2B, I think it needs to be said up front that none of the described changes actually make the
application truly interactive any sooner. It just an illusion to the user. To actually make the first
page more interactive sooner would require optimization tools that (AFAIK) don't exist for Polymer --
dead code analyzer to guide vulcanize, or the ability to identify a bundle of components as critical
and one ore more others as something to be async, etc. Waiting even 2 seconds for a page is
just too long.

This is a complex topic because there's multiple states to consider: first paint, meaningful first paint, and fully interactive. It's possible to get a fast first paint that just shows the shell of the page but doesn't have any content, this is "ok" but it would be better to have a _meaningful_ first paint where you're not only loading the shell of the page but also the text content I came to read. Then there's the fully interactive state where you've basically got the whole site pulled down. It would be awesome to be able to get to fully interactive state right away but depending on how much JS youre loading that just might not be possible. Getting to a good first paint or meaningful first paint is a noble goal and what we're striving for with these perf patterns. Hypothetically, using the perf patterns, you could yourself differentiate between a set of critical and non-critical elements and load them separately. This is an area we're still exploring but what we don't want to do is block the entire page waiting on the fully interactive state. Being able to read something on screen is better than just starting at a white page. IOW, don't let the perfect be the enemy of the good.

**Comment by addyosmani** [comment]
The recipe helps with perceived performance optimisation which can still add a great deal of value compared to the default state one would otherwise ship with PSK today. There's definitely a lot more that could be done here. Rob: noticed you created an issue to improve the recipe. Do you want to track desired improvements there or are there specific bits you want to tackle from this issue?

**Comment by robdodson** [comment]
I was planning to just tune up the missing bits of the recipe. Right now it doesn't quite work. I'm not planning to tackle specific points from this issue.

**Comment by mdagit** [comment]
Just to be clear, I wasn't trying to say that what this doc says is not useful, rather that it could be better contextualized.
Here is some proposed verbiage:

-----
This document describes a method to substantially improve the time-to-first-paint (aka fast-first-render)
for a Polymer-based web application, typically from seconds to subsecond, basically by making the
polyfill and all elements be loaded asynchronously.

Note that while this definitely improves user perceived responsiveness, the application is not actually fully
interactive any sooner, because the same number of bytes is still brought down.
To reduce the bytes downloaded would require other techniques, such as breaking it up into major bundles of functionality
(see https://github.com/PolymerLabs/web-component-shards ) or by "tree shaking" to remove dead code.

Note also that since this is focused on a fast-first-render, you would probably be interested on how to make
your placeholder html appear as quickly as possible. For some insights into that, see for example 
   https://developers.google.com/speed/articles/reflow
   https://jakearchibald.com/2016/link-in-body/
----

btw also, i'd really like it if someone would document what really happens when the polymer polyfill is loaded
into a browser such as Chrome that already has a native implementation. As far as I can see,
webcomponents-lite.js has code like
     if (typeof WeakMap === 'undefined') {
     ...
so loading it into a browser with a native implementation does not get it overridden. But I don't know if that
is universally true. I also don't know if as of today there is anything at all in webcomponents-lite.js that it adds
to Chrome 46+.

So with that information, if someone wanted to, they could even decide to sniff the User-Agent string on the server side
and not even send back a script element to bring in the polyfill, if they wanted to get really ugly.
We all know feature testing is better than agent name testing, but we also all know there are limitations to feature testing
(or more people would like GNU configure), and optimizing for a few agent strings would cover a substantial proportion
of a user base.

-mda

**Comment by robdodson** [comment]
We've rolled many of the perf patterns into the default PSK build. By relying on the [PRPL pattern](https://www.polymer-project.org/1.0/toolbox/server) to lazy load elements on-demand we should now be increasing time to first interactive paint.
