### ISSUE TITLE
anchor link is not working

### ISSUE THREAD

**Issue by Kumassy** [PolymerElements/polymer-starter-kit#706]
I updated some code of index.html.
Here is my code:
```html
.
.
.
<section data-route="home">
  <paper-material elevation="1">
  .
  .
  .
   </paper-material>
  <a href="/contact#contact">anchor linking</a>       <!-- add -->
</section>
.
.
.
<section data-route="contact">
  <paper-material elevation="1">
    <h2 class="page-title" id="contact">Contact</h2>     <!-- add id-->
    <p>This is the contact section</p>
    <a href="#contact">anchor linking</a>      <!-- add-->
  </paper-material>
</section>

```
But Chrome shows wrong url such as "http://localhost:5000/#contact","http://localhost:5000/contact#!/contact#contact" when clicking `<a href="#contact"></a>` and `<a href="/contact#contact"></a>`.

Any idea?

**Comment by robdodson** [comment]
what's the desired outcome that you'd like it to show?

**Comment by Kumassy** [comment]
I hope usual behavior like static pages.
When clicking `<a href="#contact"></a>` in `http://localhost:5000/#!/contact`,brower should scroll to `#contact`.
When clicking `<a href="/contact#contact"></a>` in `http://localhost:5000`,brower should jump to `http://localhost:5000/#!/contact`and scroll to `#contact`.

But my code gives undesired outcome.

**Comment by samccone** [comment]
Hi @Kumassy since this app is a SPA, the # jumping will not work, instead you will want to write some custom router middleware that after rendering the page will locate the element matching the # selector and scroll it into view...


here is an example in an app I did a while ago
https://github.com/twosigma/beaker-notebook-www/blob/master/assets/js/views/getting-started.js#L29



Good luck!

**Comment by Kumassy** [comment]
@samccone 
thanks!
