### ISSUE TITLE
Use npm throughout, instead of npm & bower?

### ISSUE THREAD

**Issue by dandv** [PolymerElements/polymer-starter-kit#728]
http://stackoverflow.com/a/31219726/1269037

**Comment by samccone** [comment]
Thanks for the issue! :) This is something that is in progress cross stream.
When this https://github.com/Polymer/polymer/issues/326 rollout happens we will switch.

**Comment by dandv** [comment]
Thanks @samccone. Are there plans for [ditching gulp](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/) too?

**Comment by samccone** [comment]
somewhat yes, 

https://github.com/PolymerElements/polymer-starter-kit/issues/653

see tooling
https://blog.polymer-project.org/announcements/2016/02/16/2016-roadmap/

**Comment by abdonrd** [comment]
@samccone there are any dates about https://github.com/Polymer/polymer/issues/326 rollout?

**Comment by robdodson** [comment]
@abdonrd the packages are registered on npmjs.com/~polymer. I think justin mentioned in that thread that he put together an example app but as we said in the thread, we don't have a great strategy for solving the conflict resolution issue. The community members wanted us to publish to npm and let the community try to work through a solution so that's the current plan at the moment. I guess this is a long way of saying that we're not actively working on a conflict resolution tool for npm, though if no one in the community puts one together we very likely will eventually take a crack at it. Just not sure when that will be.

**Comment by samccone** [comment]
cc @sebmck

**Comment by dandv** [comment]
Just ran into this again - I didn't have bower installed globally, and `polymer init` failed.

**Comment by robdodson** [comment]
@FredKSchott I think this would be a good thing for Polymer CLI to detect (that bower isn't globally installed) and warn about that.

**Comment by FredKSchott** [comment]
It should currently warn (because the bower command fails) but this is easy to lose in the other output. I have a branch sitting around somewhere that was half-way towards adding an install `Y/n` prompt, we could revisit that solution if enough people are hitting this.
