### ISSUE TITLE
[PSK2] Add polybuild task

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#785]
I think it would be interesting to add `polybuild` as gulp task.

Opinions?

cc @robdodson @chuckh @samccone

**Comment by robdodson** [comment]
@justinfagnani will the CLI leverage polybuild?

**Comment by abdonrd** [comment]
@robdodson @justinfagnani that would be awesome! 🙏

**Comment by justinfagnani** [comment]
@rob I don't think so. So far I've built something a little different than polybuild to allow users to plug in their own steps from their gulpfile. I might fold it back into polybuild, but since polybuild is just a CLI wrapper around some gulp steps we might just deprecate it in favor of polytool so that we don't have so many CLIs.

**Comment by addyosmani** [comment]
To minimise confusion, we want to get as aligned as possible with the tooling story presented by Polytool in this case. I don't think we should try integrating polybuild here until it's clear what it's future is going to be (we've been burned by it in the past and I have faith in what Justin is putting together).

**Comment by abdonrd** [comment]
Yes! It seems that we all think alike. Closed in favor of `polytool`!
