### ISSUE TITLE
PSK2 Have the code that does lazy loading of webcomponentsjs either at Polymer or Polyfill level rather than in the app

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/polymer-starter-kit#824]
Referring to [this commit](https://github.com/PolymerElements/polymer-starter-kit/commit/0f40fe982951fec0ffb6f7a4bb01a25a92a296ee) aimed at only loading the polyfills if they are necessary, wouldn't it make sense to have `webcomponentsjs` to run this check so that we _always_ load `webcomponentsjs` (therefore getting a much cleaner index page)?

I most likely made a fool of myself once again opening [this issue](https://github.com/webcomponents/webcomponentsjs/issues/531) on the webcomponens repo.

In general, my main concern is that it would be better not to have this kind of low-levelish code in the *app*, but keep it at Polymer level or polyfill level.

Disclaimer: this is posted in the most humble fashion.

**Comment by mercmobily** [comment]
(In the meantime, if somebody could explain this if to me:

        if (!window.HTMLImports) {
            document.dispatchEvent(
                new CustomEvent('WebComponentsReady', {bubbles: true}));
          }

I will be immensely grateful. I don't get it: `onload()` gets called either way, either once the polyfill is loaded or by calling it directly.

So... why why do you then check if !window.HTMLImports? If The browser doesn't need polyfills, then that event should come from the browser itself, right? And again why checking `window.HTMLImports` rather than `webComponentsSupported` which is in the same scope?

**Comment by abdonrd** [comment]
We can't add this code, because we make this check in the PSK2 to avoid download the webcomponentsjs file if the browser supports Web Components.

And here you can find a code explication: https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/polymer-perf.md#polymer-performance-recipe 😃

**Comment by jsilvermist** [comment]
But what about in Polymer? Polymer is always downloaded, so couldn't this (at least the part about firing the WCR event) be added to Polymer's initiation?

**Comment by TimvdLippe** [comment]
This snippet is indeed intended to save the useless download which leads to a reduction in file size. If you would move this code to the file, you still load the whole file to discover that you do not need it.

About the onload function: If your browser requires the polyfill, you would need to listen for the `WebComponentsReady` event until you can register your elements. Therefore to make your code compatible with the polyfill, you see `window.addEventListener('WebComponentsReady', callback)`. In other words: Once the polyfill finished, call this function.

However, this would completely break if you are NOT loading the polyfill. Since the polyfill fires this event, not loading will not fire the event. The callback will therefore never be called and your application remains blank. Therefore, if you are not polyfilling, you have to manually fire the event. `!window.HTMLImports` is to check if you are NOT loading the polyfill. The polyfill populates this field on `window`.

**Comment by mercmobily** [comment]
@TimvdLippe @abdonrd Couldn't this happen at webcomponentsjs level then? When you load webcomponentsjs, you are actually loading this snippet which checks whether you actually need it or not. If you do, then it loads it. If you don't, it fires the event manually. If you do, it loads the actual polyfills... I think something like this would make total sense in webcomponentsjs, rather than having to repeat this very same code in every single app using webcomponentsjs/polymer...

**Comment by mercmobily** [comment]
@TimvdLippe Ah I thought the specs also got the browser to fire `WebComponentsReady`... hence my confusion!

**Comment by robdodson** [comment]
> Couldn't this happen at webcomponentsjs level then? When you load webcomponentsjs, you are actually loading this snippet which checks whether you actually need it or not. If you do, then it loads it.

I think the issue largely has to do with wanting to avoid HTTP requests as they can be quite expensive.

It's totally possible for webcomponents-lite.js to contain this check in a scout file, which then lazy loads webcomponents-lite.js if it doesn't pass, but then you're incurring 2 http requests (one for the scout and one for the polyfills).

**Comment by mercmobily** [comment]
Rob: OK, point taken. But then, can't we add this at Polymer level? The only thing that would possibly be painful is that it would need to make assumptions on where `webcomponentsjs` is located on the server...

**Comment by robdodson** [comment]
I don't think so because we have to use html imports to load Polymer

**Comment by mercmobily** [comment]
Ah, true, nevermind...!
