### ISSUE TITLE
Should elements import polymer at the top

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#89]
I noticed `my-list` and `my-greeting` don't have imports for polymer at the top of their definitions. I was wondering if that was done on purpose, and if not, if it would be ok to add those?

**Comment by addyosmani** [comment]
This was done on purpose. The last few versions of vulcanize have failed to correctly handle cases where the polymer import is at different levels (e.g bower_components/polymer/polymer.html vs ../../bower_components/etc). I'll double check if this is a known issue upstream.

**Comment by addyosmani** [comment]
@azakus interested in your opinion on a pattern.

The element's catalog currently explicitly specifies polymer.html as an import at the top of their [elements.html](https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/elements.html) file, but doesn't do so for each of the other child elements used in the app. For example, [app-cart](https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/app-cart/app-cart.html) and [app-bar](https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/app-bar/app-bar.html).
This effectively works fine atm, both at runtime and during vulcanization.

In Starter Kit, we use a similar pattern, not including the import for polymer.html at the top of any boilerplate elements we include out of the box. 

One of the reasons we do this is down to a (possible?) bug with vulcanize whereby if `elements/elements.html` included a reference to polymer.html and `elements/my-list/my-list.html` included a reference to polymer.html, you have two slightly different paths to the same import. I had assumed vulcanize would dedupe refs/inclusions to the same import at different paths, but ran into bugs here that required us to just include polymer.html once rather than at different paths per import. Does that make sense? Known issue?

**Comment by azakus** [comment]
I'm not sure I follow, but the imports have to resolve the the same absolute path in order to be deduplicated. This is true of both vulcanize and HTML Imports in general.

There were a few bugs that were quashed recently, so please make sure you are using vulcanize 1.9.1, or gulp-vulcanize 6.0.1

**Comment by addyosmani** [comment]
Thanks! That confirms something I was curious about. I'll also double check we're on latest.

**Comment by robdodson** [comment]
Just wanted to check in on this? I think I recall in a different discussion that perhaps this is working so long as we're on the latest vulcanize?

**Comment by addyosmani** [comment]
Do you have link to that discussion by any chance? :)

**Comment by robdodson** [comment]
Looking around in my email, I don't see anything. Very possible I imagined it :stuck_out_tongue_winking_eye:  Did you try the latest vulcanize/gulp-vulcanize yet?

**Comment by addyosmani** [comment]
Not yet! To test we'll want to re-add all refs to the top of imports, bump vulcanize and see if anything breaks. I'll do this this week unless anyone gets to it before I do.

**Comment by notwaldorf** [comment]
@addyosmani you win owning this bug since you're the most active on it. Merry Christmas! :christmas_tree:

**Comment by addyosmani** [comment]
:see_no_evil:

**Comment by ebidel** [comment]
How's this coming? There's an open question in our ES6+PSK codelab on why PSK doesn't import polymer.html in its elements and since we recommend everyone else do so, PSK should really be doing it too.

**Comment by samccone** [comment]
☺️ I'll take a look this afternoon

**Comment by chuckh** [comment]
I did some testing on this with PSK from the master and PSK 1.0.3 using Yeoman Generator for Polymer.  I used gulp-vulcanize 6.0.1 latest release and vulcanize version 1.10.3. or 1.10.4 I found the following:

In PSK 1.0.3 or PSK master adding below imports to my-greeting.html
```
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/paper-button/paper-button.html">

<dom-module id="my-greeting">
  <template>
```
1. gulp serve worked
2. gulp, gulp:serve:dist both worked which do vulcanize
3. gulp local:test gets error: 404 GET /components/polymer-starter-kit/app/bower_components/polymer/polymer.html

@robdodson I notice if you have `use strict` in custom element like below which `yo polymer:el my-element` does:
```
  <script>
  (function() {
    'use strict';
```
you get an error `Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: /Users/chuckh/DevPolymerLocal/ygp1/app/elements/my-element/my-element.html`

`line 28  col 3  Missing 'new' prefix when invoking a constructor.`

Hope this helps with troubleshooting this @samccone.

**Comment by samccone** [comment]
oh awesome @chuckh thanks for doing this. so the JSHint error seems to be a distinct issue that is unrelated.

The local:test error however does seem to be relevant (: hopefully will be able to get this one locked down today :lock: :key: :hand:

**Comment by samccone** [comment]
So yes adding these does cause a 404 when running under the tests :fire: 

the url being used:
`http://localhost:2000/components/polymer-starter-kit/app/bower_components/polymer/polymer.html`

where we expect:
`http://localhost:2000/bower_components/polymer/polymer.html`

However this does not cause tests to failure since we are already loading polymer on the test page thus allowing everything to work.

To me this is more of a consumption issue in WCT and not on our side.
As I understand components should load their dependencies relative to their current path on the FS, and any consumer of the components should correctly resolve the relative paths and or compile all of the components into the correct state (vulcanize) phase :guardsman:

I am going to defer on the correct way to configure WCT so it takes care of this for us but I think adding these is fine for the time being and we can update our WCT config async to this issue.

Thoughts? :thought_balloon: :goat:
