### ISSUE TITLE
Embedly not working on Chrome with Polymer Starter Kit 2.0.1

### ISSUE THREAD

**Issue by hakaseren** [PolymerElements/polymer-starter-kit#923]
Starting with a clean version of the Polymer Starter Kit 2.0.1, I was attempting to implement some Embedly cards by simply adding the following two lines of code as described in the Embedly official [documentation:](http://docs.embed.ly/docs/platformjs)

`<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>`
`<a href="http://embed.ly" class="embedly-card">Embedly</a>`

Everything is working fine on Firefox and Edge, but cards are not loading on Chrome.

Also, when using Polymer Starter Kit 1.3.0, there is absolutely no problem with all browsers, including Chrome.

Is there an operation I missed to make Emdedly work with Chrome and Polymer Starter Kit 2.0.1?

**Comment by robdodson** [comment]
Are you adding those lines in index.html or inside another component? Any
errors in the console in chrome?

**Comment by hakaseren** [comment]
Thanks for your reply. I am adding these two lines inside the "my-view1" component. And there is no message in the Chrome console.

**Comment by robdodson** [comment]
Since this is only happening in chrome it's probably because native shadow
dom is blocking the included script from querying for the anchor. In shadow
dom an element's markup is encapsulated. If the platform.js script is doing
something like document.querySelector() it won't be able to find your
anchor. You might check to see if there's a way to tell the emedly object
which element to attach to using your own JavaScript

**Comment by robdodson** [comment]
Going to close this as it's not a starter kit issue, it sounds like this is just a general issue with Embedly's library and Shadow DOM
