### ISSUE TITLE
icon-set should have a unique name instead of `icons`

### ISSUE THREAD

**Issue by Scarygami** [PolymerElements/polymer-starter-kit#934]
When using any element that uses `iron-icons` directly, the iron-icons icon-set won't be registered correctly because an icon-set with the name `icons` already exists, resulting in icons that are not part of the `my-icons.html` being not displayed at all.

I will prepare a PR for this issue. All that is necessary is renaming the iconset to `my-icons` and prefixing all icons in use (which is only the menu icon anyway) with `my-icons:`.

**Comment by robdodson** [comment]
@Scarygami have you had a chance to work on PR for this?

**Comment by Scarygami** [comment]
Ah, thanks for the reminder, PR is in now :)

**Comment by tony19** [comment]
@robdodson What's the schedule for the next release of PSK? (Hopefully soon? 😉 ) I've noticed several reports of this bug recently (as seen in Slack, the `<iron-icons>` repo, and Stack Overflow). It would be great to publish this fix, so that `polymer init starter-kit` produces a codebase without this bug.

**Comment by robdodson** [comment]
Just put out a new release
