### ISSUE TITLE
[REQ] Baked in global configuration

### ISSUE THREAD

**Issue by stramel** [PolymerElements/polymer-starter-kit#943]
Found while making a handful of apps that there was always a need to generate a global configuration that could contain stuff like `baseUrl`s, `logoUrl`s, and various configuration flags (crude feature toggles).

Could this be something that is baked into the PSK?

**Comment by Borjagodoy** [comment]
I work around this in a real project in my company and we declared a file app.config.js  in the src folder where we put all globals variables. This js is importing in the index of app and the host component-app pass this globales variable of config file to all components of the app. 

I don't know if is the best practise but resolved the problem :)

**Comment by stramel** [comment]
There are various ways to handle it. I have handled it by exposing a global variable in a JavaScript file that is pulled into the app-shell with an html import. Again, not sure what the "best practice" is.

My request here is just to get something built into the PSK that can help drive a best practice and not have to re-create this on each application.

**Comment by robdodson** [comment]
I don't think this is something we'll bake into PSK2 primarily because we want to keep PSK very very simple. It's just meant to be a starting point for folks to play around with Polymer and some PWA features. A big complaint we had in PSK1 was that it was too complex and folks would open it up and just delete everything.

If this is something you're doing a lot I might suggest you create your own generator for Polymer CLI. I put together a video on how to do this here: https://www.youtube.com/watch?v=A_OEdyhgnKc&index=4&list=PLNYkxOF6rcIDdS7HWIC_BYRunV6MHs5xo
