### ISSUE TITLE
Recipe for Cordova

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/polymer-starter-kit#952]
Could you help me with recipe for Cordova?

How improve PSK for working with Cordova?

**Comment by web-padawan** [comment]
Have a look at https://github.com/Collaborne/polymer-cordova-aware

**Comment by JosefJezek** [comment]
This behavior only detect Cordova environment...

**Comment by robdodson** [comment]
Cordova is not something we've actively pursued, preferring instead to encourage folks to build progressive web apps. I'm not personally very familiar with Cordova but can you explain the problems you're having? Rather than try to get all of Polymer Starter Kit working in it, have you tried starting smaller and just getting a single element to work and then building up to something the size of PSK?

**Comment by abdonrd** [comment]
Personally, I'm also in favor of Progressive Web Apps.

Anyway, probably the best option is create a new Polymer CLI template.
