### ISSUE TITLE
Suggest refactor src into m,v,c sub-directories.

### ISSUE THREAD

**Issue by JoeCodeswell** [PolymerElements/polymer-starter-kit#962]
### Description
**Suggestion**

I'd love it if Polymer were to be MVC oriented. I.e if the starter kit had appropriately adjusted imports, routes, build scripts and sample javascript M & C modules with sample linkage.

Thanks in advance.
Love and peace,
Joe
### Expected outcome
Thoughtful consideration of the developers

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by JoeCodeswell** [comment]
**Suggestion**

I'd love it if Polymer were to be MVC oriented. I.e if the starter kit had appropriately adjusted  imports, routes & sample M & C modules with sample linkage.

Thanks in advance.
Love and peace,
Joe

**Comment by robdodson** [comment]
Hi @JoeCodeswell, thanks for the issue. The project structure was decided on based on lengthy discussion with the Polymer CLI team so I don't think we can change it. Having said that, this is just meant as an example project so feel free to fork it and create/share your own version.

**Comment by JoeCodeswell** [comment]
Thanks, Rob. Do you know if "Polymer 2.0" starter-kit will include **M**V**C** support?

**Comment by web-padawan** [comment]
IMO, it would be much better to create a version of `polymer-redux-starter-kit` for Polymer 2.0
There is [this one](https://github.com/Schibum/polymer-redux-starter-kit), but it uses IMD ans System.js which is uncommon for Polymer projects.

**Comment by robdodson** [comment]
@JoeCodeswell no it will use the same structure. Polymer itself doesn't really follow an MVC pattern since we tend to not create controllers. More often the app is composed of Mediators which drive dumb components. I guess this is closer to a [MVVM](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel) approach, although we often don't create explicit models either (not that you couldn't, but it's just not something our team tends to do when we build apps).

@web-padawan I doubt we'll be creating additional starter kits/boilerplates. We would rather encourage the community to create and share their own starter kits so it doesn't feel like we're dictating the approach.
